### ISSUE TITLE
Missing style scope for header in the Kitchen Sink test page

### ISSUE THREAD

**Issue by platosha** [vaadin/vaadin-grid#1306] opened 2018-05-24 10:47 UTC
### Description

When using the Kitchen Sink page in Material Theme repo on Firefox / Edge / IE, the header cells are missing the `style-scope vaadin-grid` classes. At the same time, the style scope is applied to body cells.

### Expected outcome

The header looks the same as in Chrome.

### Actual outcome

The visual appearance of the grid header is different, the theme is not getting applied to the header cells.

### Steps to reproduce

1. Run `polymer serve` in the Material Theme repo: https://github.com/vaadin/vaadin-material-theme
2. Open `test/sink.html` in Chrome and Firefox
3. Compare the look.

### Browsers Affected

- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [x] Edge
- [x] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by jouni** [comment] 2018-05-24 10:58
I believe this is a duplicate of #1227

**Closed** 2018-05-29 08:07 UTC
Labels: bug, in review
