### ISSUE TITLE
Button to hide columns does not work for Shadow DOM.

### ISSUE THREAD

**Issue by freshp86** [vaadin/vaadin-grid#326] opened 2016-02-15 07:48 UTC
When configuring Polymer to use the real Shadow DOM (instead of shady DOM), columns can't be hidden anymore.

```
<script>
  window.Polymer = window.Polymer || {};
  window.Polymer.dom = 'shadow';                                                                                                                                                          
 </script>
```

**Comment by jounik** [comment] 2016-02-15 07:58
Thanks for the report!

The styles are broken, and some event handling logic fails to recognize clicks inside the dropdown. You can use the arrow keys and enter to toggle the hiding.

**Comment by milesje** [comment] 2016-06-17 15:51
Like wise I have placed a vaadin-grid inside of my custom element and now I am unable to hide/show hideable columns. I am not able to use the arrow keys and enter to toggle the hiding either.
![image](https://cloud.githubusercontent.com/assets/537359/16156344/6fd7e178-3479-11e6-9654-a4336332d7e7.png)

**Comment by Saulis** [comment] 2016-07-29 08:41
I was not able to reproduce the issue using the latest version using:

```html
<!doctype html>
<html>

<head>
  <script>
    window.Polymer = window.Polymer || {};
    window.Polymer.dom = 'shadow';
  </script>

  <script src="bower_components/webcomponentsjs/webcomponents-lite.js"></script>
  <link href="bower_components/vaadin-grid/vaadin-grid.html" rel="import">
</head>

<body>
  <dom-module id="x-foo">
    <template>
      <vaadin-grid id="grid" items="[[employees]]">
        <table>
          <colgroup>
            <col>
            <col hidable>
            <col hidable>
            <col>
          </colgroup>
          <thead>
            <tr>
              <th>Name</th>
              <th>Surname</th>
              <th>Activity</th>
              <th>Target</th>
            </tr>
          </thead>
        </table>
      </vaadin-grid>

    </template>
    <script>
      Polymer({
        is: 'x-foo',

        ready: function() {
          function random(arr) {
            return arr[Math.floor(Math.random() * arr.length)];
          }

          var employees = [];
          var names = ['Artur', 'Patrik', 'Henrik', 'Teemu'];
          var surnames = ['Signell', 'Lehtinen', 'Ahlroos', 'Paul'];
          var activities = ['Design', 'Implement', 'Polish', 'Deliver'];
          var targets = ['soup', 'Vaadin', 'dog', 'world peace'];
          for (var i = 0; i < 400; i++) {
            var row = [random(names), random(surnames), random(activities), random(targets)];
            employees.push(row);
          }

          this.employees = employees;
        }
      });
    </script>
  </dom-module>
  <x-foo></x-foo>
</body>

</html>
```

Closing this issue as it looks like solved to me, please feel free to reopen if there is something I've missed.

**Closed by Saulis** 2016-07-29 08:41 UTC
