### ISSUE TITLE
Integrate with scopedElements

### ISSUE THREAD

**Issue by Dixit199213bafna** [vaadin/vaadin-grid#1718] opened 2020-04-21 14:40 UTC
### Description
I am trying to use the vaadin-grid in my application. I am using below link for reference.
```
https://open-wc.org/guide/
```
Here there is a concept of scopedElement i see in in your application you try to use the element name vaadin-grid to find match or find element for example
```
_findHostGrid() {

    let el = this;

    // Custom elements extending grid must have a specific localName

    while (el && !/^vaadin.*grid(-pro)?$/.test(el.localName)) {

    el = el.assignedSlot ? el.assignedSlot.parentNode : el.parentNode;

    }

    return el || undefined;

}
```
this fails as with scoped elements it appends few extra parameters to tag name
```html
<vaadin-grid-1234>......</vaadin-grid-1234>
```

### Expected outcome
To load the grid

### Actual outcome
It gives me a error saying 
```
Cannot read property '__updateHeaderFooterRowVisibility' of undefined
    at HTMLElement._pathOrHeaderChanged (vaadin-grid-column.js:378)
    at Object.runMethodEffect [as fn] (property-effects.js:825)
    at runEffectsForProperty (property-effects.js:157)
    at runEffects (property-effects.js:121)
    at HTMLElement._propertiesChanged (property-effects.js:1708)
    at HTMLElement._flushProperties (properties-changed.js:360)
    at HTMLElement._flushProperties (property-effects.js:1552)
```

### Browsers Affected

- [ *] Chrome

**Comment by web-padawan** [comment] 2020-04-21 18:00
Sorry for inconvenience, for now we recommend using `vaadin-1234-grid`

Closing as duplicate of #1589.

**Closed by web-padawan** 2020-04-21 18:00 UTC
