### ISSUE TITLE
Grid with component renderer shows empty rows on chrome 72

### ISSUE THREAD

**Issue by bbaumgartner** [vaadin/vaadin-grid#1563] opened 2019-02-15 07:29 UTC
### Description

Given:

        @Route("grid")
        public class GridView extends VerticalLayout {
        
            public GridView() {
                setSizeFull();
        
                Grid<Object> grid = new Grid<>();
        
                grid.addColumn(new ComponentRenderer<>(row -> {
                    VerticalLayout result = new VerticalLayout();
        
                    Label label = new Label("Row " + row.toString());
                    result.add(label);
        
                    return result;
                })).setHeader("Component Renderer");
        
                grid.setItems(IntStream.range(0, 500).boxed().collect(Collectors.toList()));
        
                add(grid);
            }
        }

### Expected outcome

Show the grid with the rows:
![screenshot 2019-02-15 at 08 21 01](https://user-images.githubusercontent.com/6337810/52840798-afbf0700-30fa-11e9-842e-3b8858c5d528.png)

### Actual outcome

On chrome 72.0.3626.109:
![screenshot 2019-02-15 at 08 22 18](https://user-images.githubusercontent.com/6337810/52840855-d715d400-30fa-11e9-9547-47ad454ed42b.png)

### Live Demo

Well, not exactly the same but I think it is related:
1. Open with chrome 72: https://admin-ui-demo.comerge.net/card-view
2. Switch to simple view
3. Switch to card view
* IS: The first card is Aaliyah Lohmann
* SHOULD: The first card is Aaliyah Alizadeh
Now resize the browser window until the first card magically pops up

![example](https://user-images.githubusercontent.com/6337810/52841142-c2860b80-30fb-11e9-8a02-f92e97d81051.gif)

### Browsers Affected

As far as I see only Chrome 72 is affected, it works in all other browsers, including chrome 71 and chrome canary

**Comment by bbaumgartner** [comment] 2019-02-15 07:30
Oh yeah, that's with vaadin 12.0.6/ grid 2.1.5

**Comment by web-padawan** [comment] 2019-02-15 13:48
Duplicate of vaadin/flow#5025 which is already fixed in Flow. The fix to be backported to V12.
We understand the importance of this issue so the team will take care of landing the fix ASAP.

**Closed by web-padawan** 2019-02-15 13:48 UTC

**Comment by bbaumgartner** [comment] 2019-02-15 15:17
Thank you Serhii
