### ISSUE TITLE
Vertical scrollbars not visible in Chrome

### ISSUE THREAD

**Issue by fadfood** [vaadin/vaadin-grid#191] opened 2015-09-30 10:31 UTC
I have implemented vaadin-grid and binded the source on the fly. I only see the vertical scroll bar when I use the down key on the last item. How to always show the vertical scroll bar?

**Comment by jounik** [comment] 2015-09-30 12:20
There seem to be bugs with scrollbars, they should work as expected without any extra work.

**Comment by jounik** [comment] 2015-11-20 11:21
Duplicate of #243

**Comment by jounik** [comment] 2015-11-25 11:02
Reopening as #243 ended up being a separate issue after all. This issue is just about Chrome.

Also, as a clarification to the original comment: the scrollbars in the grid should function almost identically as the native OS scrollbars. So on OS X, if you have the default scrollbar behavior that only shows them while you scroll, the grid adopts the native behavior.

**Comment by jounik** [comment] 2015-11-25 11:44
Recorded a video of the erratic behavior. It seems like the scrollbar is invisible every other time, and every other time it works correctly:

https://dl.dropboxusercontent.com/u/427102/screenshots/vaadin-grid-scrollbars-chrome.mov

**Comment by jouni** [comment] 2017-03-23 09:00
Wontfix. The upcoming 2.0 version should not suffer from this bug any more.

**Closed by jouni** 2017-03-23 09:00 UTC
Labels: 1.x
