### ISSUE TITLE
TreeGrid: Refreshing parent item after removing its child doesn't show the proper hierarchy

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/vaadin-grid#1829] opened 2020-06-18 12:15 UTC
- Vaadin Framework version: 14.2

- Description of the bug
In TreeGrid, if after removing a child item one calls refreshItem() using the parent object, the parent hierarchy continues to display the removed child item.

- Minimal reproducible example
```
@Route("")
public class TreeGrid extends VerticalLayout {

    public TreeGrid() {
        TreeGrid<String> grid = new TreeGrid<>();
        grid.addHierarchyColumn(String::toString).setHeader("Name");

        String root = "Root";
        String child = "child";
        String subChild = "Sub-child";

        TreeData<String> td = grid.getTreeData();
        td.addItem(null, root);
        td.addItem(root, child);
        td.addItem(child, subChild);
        grid.expand(root, child, subChild);

        Button button = new Button("Remove first child", e -> {
            td.removeItem(child);
            grid.getDataProvider().refreshItem(root);
        });

        add(grid, button);
    }
}
```

- Expected behavior
After clicking on the button, refreshItem() should update the hierarchy so that the child and subChild are no longer displayed. 

- Actual behavior
The removed child and its children are still displayed in the hierarchy (and clickable, which causes an IllegalArgumentException).

**Comment by tulioag** [comment] 2020-12-03 17:30
Calling this method

```
    @Override
    public void refreshItem(T item) {
```

Is equivalent of calling the overloaded method with `refreshChildren = false`
```
   @Override
    public void refreshItem(T item, boolean refreshChildren) {
        fireEvent(new DataRefreshEvent<>(this, item, refreshChildren));
    }
```

Refreshing the TreeGrid recursivelly can lead to performance implications and making it the default might be considered a breaking change.

In my opinion, the real issue here is in the remove operation. 
```
    /**
     * Remove a given item from this structure. Additionally, this will
     * recursively remove any descendants of the item.
     *
     * @param item
     *            the item to remove, or null to clear all data
     * @return this
     *
     * @throws IllegalArgumentException
     *             if the item does not exist in this structure
     */
    public TreeData<T> removeItem(T item)
```

The line `td.removeItem(child);` should remove the item and all of its children, without needing to call  `grid.getDataProvider().refreshItem(root)`. This is not happening and there is an issue for that: https://github.com/vaadin/vaadin-grid/issues/1819.

**Comment by tarekoraby** [comment] 2020-12-04 06:49
Whether one calls `refreshItem(root)` or `refreshItem(root, true)` has no bearing on the issue IMO as it makes no difference here.  In the above example code, calling `td.removeItem(child);` correctly removes `child` & `Sub-child` from the hierarchy. Accordingly, calling `refreshItem(root, true);` is effectively the same as calling `refreshItem(root)`. 

> The line td.removeItem(child); should remove the item and all of its children, without needing to call grid.getDataProvider().refreshItem(root)

To clarify, calling `removeItem()` does already seem to remove the item and all of its children (recursively) from the DataProvider. And while it might be nice not having to refresh the DataProvider explicitly after the removal, the issue here remains that this removal is not reflected in the actual view even when one refreshes the parent of the removed item explicitly.

**Comment by tarekoraby** [comment] 2020-12-04 07:11
It is worth noting that the workaround mentioned in #1819 seems to also work here. One can collapse and expand the parent node after the removal of its child. In the above example, one would call:
```
td.removeItem(child);
grid.getDataProvider().refreshItem(root);

grid.collapse(root);
grid.expand(root);
```

**Comment by tarekoraby** [comment] 2020-12-04 07:28
But then again, this workaround doesn't seem to work in at least one case: namely, if (1) the removed item has children of its own  (2) the removed item was expanded to show its children, and (3) the removed item has a sibling. In such a case, collapsing/expanding the parent after the removal of its child seems to have the weird effect of moving the children of this child to its sibling. 

A workaround of the workaround is to collapse the child before its removal. Like in this example:


```
TreeGrid<String> grid = new TreeGrid<>();
grid.addHierarchyColumn(String::toString).setHeader("Name");

String root = "Root";
String childOne = "childOne";
String childTwo = "childTwo";
String subChild = "Sub-child";

TreeData<String> td = grid.getTreeData();
td.addItem(null, root);
td.addItem(root, childOne);
td.addItem(root, childTwo);
td.addItem(childOne, subChild);
grid.expand(root, childOne, subChild);

Button button = new Button("Remove first child", e -> {
    grid.collapse(childOne); // This is necessary
    td.removeItem(childOne);

    grid.getDataProvider().refreshItem(root, true);

    grid.collapse(root);
    grid.expand(root);
});

add(grid, button);
```

**Comment by tulioag** [comment] 2020-12-04 09:25
Thanks for testing this out. You are right, calling `refreshItem(root)` or `refreshItem(root, true)` makes no difference, because neither does anything. So I think the description of this issue is a bit misleading.

Looking at the documentation, my understanding is that all you would need to do is `Button button = new Button("Remove first child", e -> td.removeItem(child))` and all the subtree should be removed from the grid, not only in the data provider, but also in the client side, including removing the expand arrow, given that there are no more children. Any calls to refresh or collapse should be unnecessary.

Because of those reasons, I think this issue is the same as https://github.com/vaadin/vaadin-grid/issues/1819.

**Comment by tulioag** [comment] 2020-12-04 13:04
Closed as a duplicate of https://github.com/vaadin/vaadin-grid/issues/1819

**Closed by tulioag** 2020-12-04 13:04 UTC
Labels: Impact: Low, Severity: Major, flow
