### ISSUE TITLE
scrolling event doesn't get passed to the parent

### ISSUE THREAD

**Issue by malthusyau** [vaadin/vaadin-grid#345] opened 2016-04-03 23:53 UTC
If the grid is already scrolled to the top, scroll up events don't get passed up to the parent. This seems to be different from default behaviors of scrollable html elements. In the [demo](https://cdn.vaadin.com/vaadin-core-elements/latest/vaadin-grid/demo/datasources.html#toc_0_inline_data), in the sample code boxes (inline data for example), while scrolling down inside the sample code box, once the source code reaches the bottom, the scroll down event is passed to the parent and the page is scrolled down, but vaadin-grid doesn't do that.

**Comment by jounik** [comment] 2016-04-04 11:08
Thanks for the report. This is a duplicate of #253

**Closed by jounik** 2016-04-04 11:08 UTC
