### ISSUE TITLE
Upgrading from v3 to v4

### ISSUE THREAD

**Issue by andrewspy** [vaadin/vaadin-grid#1112] opened 2017-11-18 22:14 UTC
Apart from being a Pure Polymer 2.0 implementation in v4, is there any other changes that developer should be aware when migrating from v3?

Here's my initial drop-in replacement test from v3 to v4 shows:-

- There is an new cell selected grey border whenever a cell is selected (but it behave weirdly and differently compare to Chrome and iOS)
- `notifyResize()` doesn't work as expected in iOS (but it does working fine in Chrome)

Before I dive into the detail, just want to know if there is a migration guide from v3 to v4. Thanks!

**Comment by web-padawan** [comment] 2017-11-22 07:22
The most important change is that the CSS mixins are dropped in v4 in favor of the CSS Shadow parts (a new spec which is announced on the latest Polymer Summit to be the future). The [polyfill](https://github.com/PolymerLabs/part-theme) for that spec is still WIP, so meanwhile we rely on our own implementation with [ThemableMixin](https://github.com/vaadin/vaadin-themable-mixin/wiki).

Could you please describe steps to reproduce both issues you mentioned so we can take a look?

**Comment by andrewspy** [comment] 2017-11-30 02:28
@web-padawan Thanks for the reference on the CSS Shadow parts. I'll try to see if I can re-produce the issue by isolating the CSS mixins with a seperate test case in the next few days.

**Comment by andrewspy** [comment] 2017-11-30 09:00
@web-padawan Below is the code to produce the issue on iOS 11

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Polymer Element Test Case</title>
  <!-- Load webcomponents-loader.js to check and load any polyfills your browser needs -->
  <script src="bower_components/webcomponentsjs/webcomponents-loader.js"></script>
  <link rel="import" href="bower_components/polymer/polymer-element.html">

  <link rel="import" href="bower_components/vaadin-grid/vaadin-grid.html">
</head>
<body>
  
  <h1>vaadin-grid-v4-issue</h1>
  <!-- Test case HTML goes here -->

  <test-case>
  </test-case>

  <dom-module id="test-case">
    <template>
      Selected Item: [[selectedItem]]
      <vaadin-grid id="grid" style="height: auto;" items="[[myData]]" active-item="{{activeItem}}">
        <vaadin-grid-column width="50px" flex-grow="0">
          <template class="header">#</template>
          <template>[[index]]</template>
          <!-- <template class="footer">#</template> -->
        </vaadin-grid-column>

        <vaadin-grid-column>
          <template class="header">value</template>
          <template>[[item.value]]</template>
          <!-- <template class="footer">#</template> -->
        </vaadin-grid-column>

        <vaadin-grid-column>
          <template class="header">label</template>
          <template>
            [[item.label]]
            <div hidden$="[[!_isEql(item.value, selectedItem)]]">
              <input type="button" value="more">
            </div>
          </template>
          <!-- <template class="footer">#</template> -->
        </vaadin-grid-column>
      </vaadin-grid>
    </template>
  </dom-module>

  <script>
    window.addEventListener('WebComponentsReady', function() {
      class TestCase extends Polymer.Element {
        static get is() {
          return 'test-case';
        }

        static get properties() {
          return {
            myData: {
              type: Array,
              value: function() {
                return [
                  {value: 'a', label: 'A'},
                  {value: 'b', label: 'B'},
                  {value: 'c', label: 'C'},
                ];
              }
            },

            activeItem: {
              type: Object,
              observer: 'activeItemChanged',
            },

            selectedItem: String,
          };
        }

        activeItemChanged(item) {
          this.$.grid.selectedItems = item ? [item] : [];
          this.selectedItem = item ? item.value : '';

          this.$.grid.notifyResize();
        }

        _isEql(v1, v2) {
          return v1 == v2;
        }
      }
      
      window.customElements.define(TestCase.is, TestCase);
    });
  </script>
</body>
</html>
```

And below is the screenshot on iOS v11:-

![image](https://user-images.githubusercontent.com/3106425/33422065-4492557a-d5ef-11e7-8a99-2c904e6f72ef.png)

Notice the new grey border selection box (in label C), not sure if it's there on intention, but it's appearing on Windows Chrome as well when switching back from different tabs.

Thanks!

**Comment by madiganz** [comment] 2018-01-19 19:58
I have the same problem. It looks like rows are no longer selectable and only cells are? I really hope this is not the case.

**Comment by web-padawan** [comment] 2018-01-19 20:49
@madiganz sorry about not answering you before. The border selection box is actually the other thing, it is used for keyboard navigation with arrow keys on the desktop and shows where the focus is. See the [Selection](https://cdn.vaadin.com/vaadin-grid/4.1.1/demo/#grid-selection-demos) demos for the working code. Are you able to reproduce the issue with the code from demos?

**Comment by madiganz** [comment] 2018-01-19 21:07
After following **Selection using Active Item**, my row now shows as selected, but the "border selection box" still appears. Is there a way to hide it? Seems like there have been a lot of changes. It would be great if there was a css migration guide that showed what to use based on the mixins used before. I am trying to style odd rows using [part~="row"][odd], but it does not seem to work.

**Comment by web-padawan** [comment] 2020-05-19 12:03
We never had a chance to provide a requested CSS migration guide. Sorry about that.
Regarding the "border selection box", my comment https://github.com/vaadin/vaadin-grid/issues/1112#issuecomment-359085065 is still valid.

Closing as outdated. Please use latest version which is 5.x at the moment.

**Closed by web-padawan** 2020-05-19 12:03 UTC
Labels: documentation
