### ISSUE TITLE
grid does not render table body on safari/firefox on mac

### ISSUE THREAD

**Issue by cutout33** [vaadin/vaadin-grid#372] opened 2016-05-25 06:48 UTC
Hi,

I am using this component for few projects now and I noticed the grids are only rendered correctly on chrome/opera! the grid header is renewed correctly but not the data inside it...

does anyone know how to fix this issue?
Thanks

**Comment by tehapo** [comment] 2016-05-25 07:01
Hi,

Safari and Firefox do not yet natively support web components, so you need to be sure to include the `webcomponents.js` polyfill.

Please verify that you have included the polyfill by a line similar to this one (inside the `<head>` section of your page).
```
<script src="bower_components/webcomponentsjs/webcomponents-lite.min.js"></script>
```

**Comment by cutout33** [comment] 2016-05-25 11:39
Hi,

Thanks for your answer, but it is already there! still no table body :/ 
can you please help?

**Comment by tehapo** [comment] 2016-05-25 13:14
Ok, it's a bit hard to diagnose the problem with so little information.

Could you next
* see if there are any errors in the browser console.
* let us know how are you adding the data to the grid.
* or ideally provide a simplified [JSFiddle](https://jsfiddle.net/) that reproduces the problem.

**Comment by cutout33** [comment] 2016-05-25 19:44
OK I finally got it to work, with the following three steps all together believe it or not! this is not for one but for 4 different grids!

- move the html code for the grid to be at the end of the page.
- change the data set in the grid to array of JSON objects instead of array of arrays (even though the later was working for chrome)
-  finally use this code to initialise the grids 

> `(function() {
  	try {
  		// HTMLImports only work on FF & Safari!
    HTMLImports.whenReady(function() {
        var grid = document.querySelector('#simple');
        // Delay the setting of data inside the grid make sure the grid is available... Tis is a MUST!
        setTimeout(function() {
	        grid.items = data_array;
	        var correctHeight = data_array.length * 48 + 71;
			$('#simple').height(correctHeight);
		}, 2000);
    });
	} catch(e) {
		// here is the code that works for chrome and opera... 
		var grid = document.querySelector('#simple');
        grid.items = data_array;
        var correctHeight = data_array.length * 48 + 71;
		$('#simple').height(correctHeight);
	}
	
  })();`

**Comment by Saulis** [comment] 2016-07-29 08:18
Closing this issue for now, please reopen if something new comes up.

**Closed by Saulis** 2016-07-29 08:18 UTC

**Comment by KuhlTime** [comment] 2016-10-07 20:03
I'm having the same problem with safari as well. I have added the webcomponents-lite file and even tried using the delay cutout explained, but still not working. 

My Array looks like this:

`var items = [{court: 1, duration: 45}, {court: 4, duration: 60}]`

and all I'm doing is:

`grid.items = items;`

that works perfectly in Chrome but Safari won't display the items. 
Maybe sb. got a solution for that?!
