### ISSUE TITLE
Grid column width is calculated wrong on Safari 14.0.3 (Big Sur)

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/vaadin-grid#2177] opened 2021-05-04 06:10 UTC
### Description
When there is a horizontal scrollbar in the Grid and the Grid is scrolled to the right, a white gap appears on the right side of the grid. After moving the mouse around it will disappear again after a while.

This issue appears when the Grid is nested in another container and both are 100% height.

Without the container or without the full height the problem does not appear. 

The issue occurs only on Safari 14.0.3 (Big Sur); a potential reason for this behavior is that the translateX value is calculated incorrectly.

Tested on Vaadin version 14.4.9.
### Expected outcome
No extra white gap should appear

### Actual outcome
https://user-images.githubusercontent.com/15027701/116966103-17e86c00-acb8-11eb-84ac-202c8f5cc896.mov

### Steps to reproduce
```java
    static class DummyItem {
        private int id;

        public DummyItem(int id) {
            this.id = id;
        }

        public int getId() {
            return id;
        }

        public void setId(int id) {
            this.id = id;
        }

    }

    public MasterDetailView(@Autowired PersonService personService) {
        setSizeFull();

        VerticalLayout mainContentLayout = new VerticalLayout();
        add(mainContentLayout);

        /* #### TOOLBAR ################### */
        HorizontalLayout toolBar = new HorizontalLayout();

        ComboBox<Boolean> comboBox = new ComboBox<>("ComboBox 1");
        // comment out the next line so that only one ComboBox has a placeholder and the
        // issue is gone:
        comboBox.setPlaceholder("Placeholder 1... ");
        toolBar.add(comboBox);

        ComboBox<Boolean> comboBox2 = new ComboBox<>("ComboBox 2");
        comboBox2.setPlaceholder("Placeholder 2... ");
        toolBar.add(comboBox2);
        mainContentLayout.add(toolBar);

        /* #### DUMMY GRID ################### */
        List<DummyItem> dummyItems = new ArrayList<>();
        for (int i = 1; i <= 50; i++) {
            dummyItems.add(new DummyItem(i));
        }
        Grid<DummyItem> grid = new Grid<>(DummyItem.class);
        grid.setItems(dummyItems);
        grid.setColumns();
        grid.addColumn(DummyItem::getId);
        for (int i = 1; i <= 10; i++) {
            String columnName = "#" + i;
            grid.addColumn(item -> columnName + " Some string here, doesn't matter");
        }
        mainContentLayout.add(grid);

        // comment out the next two lines and the issue is gone:
        grid.setSizeFull();
        mainContentLayout.setSizeFull();
    }
```
### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by tomivirkki** [comment] 2021-05-04 06:31
Duplicate of https://github.com/vaadin/vaadin-grid/issues/2149?

**Comment by OlliTietavainenVaadin** [comment] 2021-05-04 06:49
> Duplicate of #2149?

I'm not sure if it's 100% the same issue based on the description, but it could likely be the same root cause. There's a test case included in this ticket, so it should be easy to check if a change affects both.

**Comment by tomivirkki** [comment] 2021-05-04 09:18
Confirmed the issues to be the same. Since the problem is caused by a bug in Safari that seems to be really difficult to workaround, this may need to be closed as wontfix.

**Comment by jouni** [comment] 2021-05-04 14:40
This issue can be seen in our docs grid examples as well, at least on iOS.

**Comment by sissbruecker** [comment] 2021-05-04 16:18
Have been debugging this today and it really looks like a browser bug so far:
- added logging for the `scrollWidth` of the table element, which always reports `1100px`, which is correct given that there are 11 columns with `100px` each. Still the actual scrollable area and the scrollbars themselves are larger than that
- translating the table body by `-50px` completely hides the first column, however at this point the column should at least be partially visible (again, column has `100px` width). This would indicate that there is some mismatch between what the browser draws and what it reports through the element APIs
- there is a [piece of code](https://github.com/vaadin/web-components/blob/master/packages/vaadin-grid/src/vaadin-grid-scroll-mixin.js#L319) in the grid which fixes the issue when called, but then hovering the cursor over elements or just clicking somewhere breaks it again
- as Tomi mentioned, this only happens when the grid is child of a flex container

I also tried some workarounds like positioning the grid absolutely to force it out of the layout, but that did not help.

**Comment by sissbruecker** [comment] 2021-05-05 15:10
After discussing this internally we are going to close this as a won't fix.

The issue happens due to the grids usage of `position: sticky` on the individual parts of the grid (header, body, footer) as part of its internal scroll mechanism, as well as the grid being placed into a flex container. Sticky positioning in flex containers works slightly different in Safari than it does in other browsers. That results in the sticky grid parts still being scrolled natively, in addition to the internal scrolling that the grid applies, thus scrolling the grid parts by double the amount that they should. That in turn leads to the grid showing an empty space for the amount of pixels that were scrolled additionally.

The usage of `sticky` is part of the grids internal functionality that facilitates features like fixed columns, headers and footers, as well as synchronizing scrolling between all parts of the grid (header, body, footer) without a noticeable lag. As such it would be a considerable effort to move away from sticky positioning and it might degrade the other mentioned features for all users.

In the future there might be a possibility that the Webkit team tackles the issues referenced below and aligns the sticky positioning behaviour with those of the other browsers.

The only workaround ATM would be to not put the Grid into a Flex container, though this might be pretty difficult considering it's used heavily in our layout components and that the issue only occurs for Safari users. Using the workaround in the example above did improve things in my testing, but did not fix the issue completely.

References:
- [Webkit bug report 1](https://bugs.webkit.org/show_bug.cgi?id=175029), also includes a [comment](https://bugs.webkit.org/show_bug.cgi?id=175029#c3) explaining that this behaviour might be due to an unclear spec for sticky positioning
- [Webkit bug report 2](https://bugs.webkit.org/show_bug.cgi?id=189461)
- [Basic reproduction of the issue](https://jsbin.com/namagivoku/edit?html,output), open in Safari to see the element scrolling despite being sticky

**Closed by sissbruecker** 2021-05-05 15:10 UTC
Labels: BFP, bug
