### ISSUE TITLE
Grid Column resize overlaps sorting

### ISSUE THREAD

**Issue by sswweber** [vaadin/vaadin-grid#1761] opened 2020-06-16 08:53 UTC
### Description
When sorting and resizing are enabled in the columns of a grid and the columns are close to eachother the resizing cursor overlaps the sorting icons. 
### Expected outcome
Sorting should still be possible.

### Actual outcome
Sorting the column no longer works. The Cursor changes to the resizing cursor and when clicking on the sorting icons the column gets resized.

### Steps to reproduce
1. Put a `vaadin-grid` element in the page.
2. Set first Column to a short name ("ID") with only one digit values
3. Set second column arbitrary
4. Set all columns resizable(true); sortable(true)

![vaadin grid issue](https://user-images.githubusercontent.com/54979180/84753223-01152a00-afbf-11ea-92a7-b4d48c7f92a8.png)

### Browsers Affected
Only found in Chrome so far - other browsers not tested yet

**Comment by web-padawan** [comment] 2020-06-16 09:39
Duplicate of #1439

**Closed by web-padawan** 2020-06-16 09:39 UTC
