### ISSUE TITLE
Vaadin Grid 3 not working in IE11

### ISSUE THREAD

**Issue by leobatista** [vaadin/vaadin-grid#920] opened 2017-07-06 10:32 UTC
Steps to reproduce:

1) Open IE 11 and navigate to: https://vaadin.com/elements/-/element/vaadin-grid#demos

2) Click on "TRY IT OUT" option (left menu)

3) Try to change block: 

```html
<script src="https://cdn.vaadin.com/vaadin-grid/3.0.0-alpha2/bower_components/webcomponentsjs/webcomponents-lite.js"></script>
<link rel="import" href="https://cdn.vaadin.com/vaadin-grid/3.0.0-alpha2/vaadin-grid.html">
```

to:

```html
<script src="https://cdn.vaadin.com/vaadin-grid/2.0.2/bower_components/webcomponentsjs/webcomponents-lite.js"></script>
  <link rel="import" href="https://cdn.vaadin.com/vaadin-grid/2.0.2/vaadin-grid.html">
```

Nothing appears on the 3.x versions.

**Comment by jouni** [comment] 2017-07-06 12:12
The jsfiddle probably doesn’t work because v3 (Polymer 2) uses ES6 and it isn’t transpiled. The polyserve (or polymer serve) dev servers do that for you automatically, so it should work if you run it locally. You just need to do the transpilation when deploying to production if you want to support IE11 (or Safari 9).

**Comment by johnthad** [comment] 2017-10-23 20:59
I'm using polymer build to transpile an app with a simple vaadin-grid 3.0.2 demo pointed at https://demo.vaadin.com/demo-data/1.0/people. I've never seen the build/es5-bundled directory load the page with vaadin-grid in Safari 10.1.3, and only occasionally load in IE11. When the grid page does load in IE11, the grid will not scroll nor select, and the page warns me of a slow or incomplete script. This is with Polymer 2.2 and webcomponentsjs 10.0.17.

**Comment by johnthad** [comment] 2017-10-23 21:33
Okay, I was seeing failure with `es5-bundled` on IE11 and Safari 10.1.3. Now I think it was due to something happening with my Redux dispatch. I've moved my grid element to a page that is not loaded immediately after a Redux `dispatch()`, and the grid behaves properly. I'll keep an eye on this, and update you as I discover something. Sorry if I caused a false alarm.

**Comment by web-padawan** [comment] 2020-02-20 11:35
Closing per above comment https://github.com/vaadin/vaadin-grid/issues/920#issuecomment-338803441 as the problem wasn't caused by the grid.

**Closed by web-padawan** 2020-02-20 11:35 UTC
Labels: 3.x
