### ISSUE TITLE
Scrolling within Firefox

### ISSUE THREAD

**Issue by StefanCov** [vaadin/vaadin-grid#1664] opened 2019-10-08 09:22 UTC
Hi, I opened an issue a while back ( https://github.com/vaadin/vaadin-grid/issues/1645 ) for scrolling within Firefox and the issue was closed and determined fixed. It seems that the grid is still scrolling by row height rather than font height using a mouse wheel. This means my grid is not usable as the row heights are fairly large due to large components. Should this be fixed for me?

Im using vaadin-grid-5.4.8

Just ask if you need anymore information about this problem.

**Comment by tomivirkki** [comment] 2019-10-08 09:30
Hi,
Looks like the fix landed first to 5.5.0-alpha3 so it will be in 5.5.0. The latest version is currently 5.5.0-alpha4

**Comment by StefanCov** [comment] 2019-10-08 09:35
Ah okay, yous said on the issue "backported to v5.4 and v5.0" so when the issue was closed I expected it to be fixed on my version. Is this no longer the case?

**Comment by Haprog** [comment] 2019-10-08 09:49
@StefanCov Hey, it seems we forgot to backport it. I'm checking now if it is easily backported and works. Hopefully there will be no issue and it could be out in 5.4.x and 5.0.x soonish.

**Comment by StefanCov** [comment] 2019-10-08 09:52
@Haprog No worries. That would be good, thank you!

**Comment by Haprog** [comment] 2019-10-14 11:19
@StefanCov Hey the fix is now available in `vaadin-grid` [v5.4.11](https://github.com/vaadin/vaadin-grid/releases/tag/v5.4.11). Please let me know if it works for you.

And sorry for the delay. We tried releasing a 5.4.x version with the fix already early last week but there was some problem with webjars.org so we were unable to deploy the related WebJars to Maven Central (for Java users), but it finally worked this morning so now the webjar is also available.

Currently in the 5.0 branch we have some problems with tests not running, so the fix will probably not get into 5.0 that soon unless we see a demand for it. Please let us know if you want the fix for 5.0.

Will close this issue for now as fixed (and duplicate of #1645).

**Closed by Haprog** 2019-10-14 11:19 UTC

**Comment by StefanCov** [comment] 2019-10-14 13:32
My Grid defaults to v5.4.8 but i've pushed it forward to v5.4.11 and it all seems to be working! Thank you very much!
