### ISSUE TITLE
Focused row should not look the same regardless of selection state

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-grid#291] opened 2015-12-11 11:48 UTC
If you focus a row with the mouse, you have no way of telling whether it is selected or not as the background is set solely from the focus style and selection does not affect it in any way

![image](https://cloud.githubusercontent.com/assets/260340/11743139/c825d930-a00d-11e5-8e90-a2537b451e99.png)

Is project A selected or not?

**Comment by manolo** [comment] 2016-08-25 05:35
Not sure about what you mean, but there is a different grey when row is selected and hovered.
So you know whether a selected row is hovered because grey is darker, and whether the row is selected because the blue border and the grey lighter. Do you suggest changing grey darkness or other approach ?

<img width="876" alt="screen shot 2016-08-25 at 07 33 31" src="https://cloud.githubusercontent.com/assets/161853/17957945/525da800-6a96-11e6-99c4-7e43ddbbe3f1.png">

**Comment by jouni** [comment] 2016-08-25 07:48
State styles:
- Focused: blue underline
- Selected: lighter gray background
- Hover: darker gray background

The background colors are directly from [Material design specs for data tables](https://material.google.com/components/data-tables.html#data-tables-interaction). The blue focus underline is our addition, as there is no specs for a focused data table row.

**Comment by jouni** [comment] 2016-08-25 07:49
The problem is more in that we do not show the selection column (checkboxes) in single-selection mode, and only rely on row styles for the selection indication.

This should be configurable, and will be fixed in the next major version.

**Comment by jouni** [comment] 2016-08-25 07:50
That said, IMO this is an invalid issue, and can be closed.

**Closed** 2017-03-23 10:42 UTC
Labels: 1.x
