### ISSUE TITLE
Vaadin-grid horizontal scroll issue in iOS 14

### ISSUE THREAD

**Issue by mikaelliptak** [vaadin/vaadin-grid#2149] opened 2021-03-19 14:05 UTC
### Description
Using iOS devices (Tested on iOS14), user is not able to scroll tables with many columns. It is not possible to scroll neither vertically nor horizontally. Scrolling works fine on Android devices. 

### Expected outcome
Grid table has to scroll properly, user cannot move the whole grid away from the screen.

### Actual outcome
Grid table is not properly scrolled, user is able to move the whole grid away from the screen.

### Live Demo
https://drive.google.com/file/d/1E_xRAncS2fxd8o2pfdVqcTpneVmweye2/view?usp=sharing

### Steps to reproduce
1. Put a `vaadin-grid` element in the page.
2. Add 10 or more columns.
3. Open the page in a Safari web browser in mobile device resolution (horizontal scroller has to be visible)
4. Start scrolling from left to right.

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [x] Safari
- [ ] Edge
- [ ] IE 11
- [x] iOS Safari
- [ ] Android Chrome

**Comment by tomivirkki** [comment] 2021-03-23 12:00
Hi, scrolling on iOS 14 was fixed in https://github.com/vaadin/vaadin-grid/pull/1791. Which version of Grid (or Vaadin Platform version) are you using?

**Comment by mikaelliptak** [comment] 2021-03-23 12:48
Hello, we use following viersions:
- vaadin version: 14.4.7
- @vaadin/vaadin-grid: 5.7.7
- vaadin-grid-flow: 4.3.7

**Comment by tomivirkki** [comment] 2021-03-23 14:06
Just tried one of our demos on iOS 14 simulator locally. Added more columns to make sure there's enough to make it overflow horizontally. Didn't encounter any issues while scrolling:

![Kapture 2021-03-23 at 16 02 40](https://user-images.githubusercontent.com/1222264/112158971-57b83000-8bf1-11eb-976f-c8ac7fe75033.gif)

You can try the same demo with the grid version you use (5.7.7) at https://cdn.vaadin.com/vaadin-grid/5.7.7/demo/#grid-columns-demos

Can you provide an isolated example project that we can use to investigate the issue?

**Comment by mikaelliptak** [comment] 2021-03-24 07:25
Thank you very much.
It looks that everything works in demo. I have to check our implementation in detail, and let you know

**Comment by mikaelliptak** [comment] 2021-03-24 14:02
Hello,
please, could you verified horizontal scroller on our platform https://platform.altfins.com/summary ?
Maybe will you be able to identify the issue.

**Comment by mikaelliptak** [comment] 2021-03-25 14:09
Hello,
I was able to identify an issue, I think. It looks that scroller does not work properly when grid has set property **setHeightByRows(true)**. There is simple code snippet to reproduce:

```
Board board = new Board();
SignalsSummaryPatternItem pattern = new SignalsSummaryPatternItem("Ascending Triangle", 1l, 2l, 3l, 0l, 5l, 6l, 2l, 18l);
SignalsSummaryPatternItem pattern1 = new SignalsSummaryPatternItem("Descending Triangle", 0l, 0l, 3l, 4l, 15l, 1l, 7l, 0l);
SignalsSummaryPatternItem pattern2 = new SignalsSummaryPatternItem("Triangle", 1l, 0l, 3l, 0l, 5l, 0l, 7l, 1l);
SignalsSummaryPatternItem pattern3 = new SignalsSummaryPatternItem("Channel Down", 0l, 1l, 0l, 4l, 0l, 6l, 1l, 1l);
List<SignalsSummaryPatternItem> patterns = Arrays.asList(pattern, pattern1, pattern2, pattern3);
TreeGrid<SignalsSummaryPatternItem> grid = new TreeGrid<>();
grid.setHeightByRows(true);

grid.setItems(patterns);
grid.addColumn(SignalsSummaryPatternItem::getFilterKey);
grid.addColumn(SignalsSummaryPatternItem::getBullValue15M).setHeader("15M Bullish");
grid.addColumn(SignalsSummaryPatternItem::getBullValue1H).setHeader("1H Bullish");
grid.addColumn(SignalsSummaryPatternItem::getBullValue4H).setHeader("4H Bullish");
grid.addColumn(SignalsSummaryPatternItem::getBullValue1D).setHeader("1D Bullish");
grid.addColumn(SignalsSummaryPatternItem::getBearValue15M).setHeader("15M Bearish");
grid.addColumn(SignalsSummaryPatternItem::getBearValue1H).setHeader("1H Bearish");
grid.addColumn(SignalsSummaryPatternItem::getBearValue4H).setHeader("4H Bearish");
grid.addColumn(SignalsSummaryPatternItem::getBearValue1D).setHeader("1D Bearish");
board.addRow(grid);
```
```
public class SignalsSummaryPatternItem {

    private final String filterKey;
    private final Long   bullValue15M;
    private final Long   bullValue1H;
    private final Long   bullValue4H;
    private final Long   bullValue1D;
    private final Long   bearValue15M;
    private final Long   bearValue1H;
    private final Long   bearValue4H;
    private final Long   bearValue1D;

    public SignalsSummaryPatternItem(String filterKey, Long bullValue15M, Long bullValue1H, Long bullValue4H,
                                     Long bullValue1D, Long bearValue15M, Long bearValue1H, Long bearValue4H,
                                     Long bearValue1D) {
        this.filterKey = filterKey;
        this.bullValue15M = bullValue15M;
        this.bullValue1H = bullValue1H;
        this.bullValue4H = bullValue4H;
        this.bullValue1D = bullValue1D;
        this.bearValue15M = bearValue15M;
        this.bearValue1H = bearValue1H;
        this.bearValue4H = bearValue4H;
        this.bearValue1D = bearValue1D;
    }

    public String getFilterKey() {
        return filterKey;
    }

    public Long getBullValue15M() {
        return bullValue15M;
    }

    public Long getBullValue1H() {
        return bullValue1H;
    }

    public Long getBullValue4H() {
        return bullValue4H;
    }

    public Long getBullValue1D() {
        return bullValue1D;
    }

    public Long getBearValue15M() {
        return bearValue15M;
    }

    public Long getBearValue1H() {
        return bearValue1H;
    }

    public Long getBearValue4H() {
        return bearValue4H;
    }

    public Long getBearValue1D() {
        return bearValue1D;
    }
}
```
Please, could you investigate the issue ?

**Comment by tomivirkki** [comment] 2021-03-25 15:46
Hi @mikaelliptak 
Thanks for the isolated test case. Seems that Board can also be replaced with HorizontalLayout (or any flexbox for that matter) and the issue would still occur. Will need to investigate further.

**Comment by tomivirkki** [comment] 2021-03-26 09:50
Ok took a closer look and isolated the example further (plain HTML/CSS): https://jsbin.com/namagivoku/edit?html,output 

There seems to be a browser bug in Safari/Webkit related to how `position: sticky` works in this specific case. The erroneous behaviour manifests differently on Grid but it's caused by the same bug.

**Expected behavior on Chrome (the content is sticky, doesn't scroll):**

![expected](https://user-images.githubusercontent.com/1222264/112613211-85d38500-8e28-11eb-82d6-cac51935a0a6.gif)

**Unexpected behavior on Safari (the content is sticky, but scrolls):**

![unexpected-safari](https://user-images.githubusercontent.com/1222264/112613314-a13e9000-8e28-11eb-9a2f-3688795b2512.gif)

**Expected behavior on Safari (the wrapper set not to be a flexbox):**

![expected-safari](https://user-images.githubusercontent.com/1222264/112613392-b5828d00-8e28-11eb-9ee2-ea16e229e86e.gif)

**Comment by sissbruecker** [comment] 2021-05-03 09:39
I started investigating this, but can not reproduce this at the moment.

First to clarify what the issue that is described here is:
- when using Vaadin 14 and iOS 14
- if the horizontal scroll area of the grid is larger than the visible area
- then the grids contents can not be scrolled horizontally
- instead the whole page is scrolled

Mind you, this does not include some other issues that are hinted at in this thread:
- vertical scrolling does not work (this is mutually exclusive by the provided example, which uses `setHeightByRows`)
- columns are not sticky

I tried to reproduce this issue with the example provided above, which I added as the following view to a Vaadin Starter (`v14.5.3`) app:

```java
package com.example.application.views;

import com.example.application.views.main.MainView;
import com.vaadin.flow.component.board.Board;
import com.vaadin.flow.component.html.Div;
import com.vaadin.flow.component.treegrid.TreeGrid;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;

import java.util.Arrays;
import java.util.List;

@Route(value = "iosscrollissue", layout = MainView.class)
@PageTitle("IOS Scroll Issue")
public class IosScrollIssueView extends Div {
    public IosScrollIssueView() {
        Board layout = new Board();
        SignalsSummaryPatternItem pattern = new SignalsSummaryPatternItem("Ascending Triangle", 1l, 2l, 3l, 0l, 5l, 6l, 2l, 18l);
        SignalsSummaryPatternItem pattern1 = new SignalsSummaryPatternItem("Descending Triangle", 0l, 0l, 3l, 4l, 15l, 1l, 7l, 0l);
        SignalsSummaryPatternItem pattern2 = new SignalsSummaryPatternItem("Triangle", 1l, 0l, 3l, 0l, 5l, 0l, 7l, 1l);
        SignalsSummaryPatternItem pattern3 = new SignalsSummaryPatternItem("Channel Down", 0l, 1l, 0l, 4l, 0l, 6l, 1l, 1l);
        List<SignalsSummaryPatternItem> patterns = Arrays
                .asList(pattern, pattern1, pattern2, pattern3);
        TreeGrid<SignalsSummaryPatternItem> grid = new TreeGrid<>();
        grid.setHeightByRows(true);
        grid.getElement().setAttribute("style", "border: solid 3px red");

        grid.setItems(patterns);
        grid.addColumn(SignalsSummaryPatternItem::getFilterKey);
        grid.addColumn(SignalsSummaryPatternItem::getBullValue15M).setHeader("15M Bullish");
        grid.addColumn(SignalsSummaryPatternItem::getBullValue1H).setHeader("1H Bullish");
        grid.addColumn(SignalsSummaryPatternItem::getBullValue4H).setHeader("4H Bullish");
        grid.addColumn(SignalsSummaryPatternItem::getBullValue1D).setHeader("1D Bullish");
        grid.addColumn(SignalsSummaryPatternItem::getBearValue15M).setHeader("15M Bearish");
        grid.addColumn(SignalsSummaryPatternItem::getBearValue1H).setHeader("1H Bearish");
        grid.addColumn(SignalsSummaryPatternItem::getBearValue4H).setHeader("4H Bearish");
        grid.addColumn(SignalsSummaryPatternItem::getBearValue1D).setHeader("1D Bearish");
        layout.addRow(grid);

        this.add(layout);
    }

    public class SignalsSummaryPatternItem {

        private final String filterKey;
        private final Long   bullValue15M;
        private final Long   bullValue1H;
        private final Long   bullValue4H;
        private final Long   bullValue1D;
        private final Long   bearValue15M;
        private final Long   bearValue1H;
        private final Long   bearValue4H;
        private final Long   bearValue1D;

        public SignalsSummaryPatternItem(String filterKey, Long bullValue15M, Long bullValue1H, Long bullValue4H,
                Long bullValue1D, Long bearValue15M, Long bearValue1H, Long bearValue4H,
                Long bearValue1D) {
            this.filterKey = filterKey;
            this.bullValue15M = bullValue15M;
            this.bullValue1H = bullValue1H;
            this.bullValue4H = bullValue4H;
            this.bullValue1D = bullValue1D;
            this.bearValue15M = bearValue15M;
            this.bearValue1H = bearValue1H;
            this.bearValue4H = bearValue4H;
            this.bearValue1D = bearValue1D;
        }

        public String getFilterKey() {
            return filterKey;
        }

        public Long getBullValue15M() {
            return bullValue15M;
        }

        public Long getBullValue1H() {
            return bullValue1H;
        }

        public Long getBullValue4H() {
            return bullValue4H;
        }

        public Long getBullValue1D() {
            return bullValue1D;
        }

        public Long getBearValue15M() {
            return bearValue15M;
        }

        public Long getBearValue1H() {
            return bearValue1H;
        }

        public Long getBearValue4H() {
            return bearValue4H;
        }

        public Long getBearValue1D() {
            return bearValue1D;
        }
    }
}
```




I can not reproduce the issue running this example in an emulator, as well as an actual iPhone, both using iOS v14. See the following screenshot that shows that the grid was scrolled horizontally indicated by showing some of the initially invisible columns. I also added a border for the grid to verify that the scrolling happened within the grid instead of the outer layout.

![IOS Scroll Issue](https://user-images.githubusercontent.com/357820/116861000-b3b7a080-ac02-11eb-848e-fe2522aab151.png)

I also tried the linked production app (https://platform.altfins.com/summary) which worked as well.

The only issue I noticed is that the horizontal scroll area on iOS seems to be about double of what is actually needed by the columns, however that would be a much less severe issue than what is described here. See following screenshot which demonstrates some empty space after the last column:

![IMG_5DA79F0F8E03-1](https://user-images.githubusercontent.com/357820/116861165-fb3e2c80-ac02-11eb-9ee5-81b5786a7e86.jpeg)

@mikaelliptak can you please confirm if you are still experiencing this issue and that you can reproduce it using this example project: [treegridscrollissue.zip](https://github.com/vaadin/vaadin-grid/files/6414041/treegridscrollissue.zip)?

**Comment by tomivirkki** [comment] 2021-05-04 06:51
@sissbruecker I think this is about the same issue https://github.com/vaadin/vaadin-grid/issues/2177#issue-875137154

**Comment by sissbruecker** [comment] 2021-05-04 08:03
@tomivirkki I don't think so: This issue is about not being able to scroll at all, whereas the other one is about the scroll area being calculated incorrectly. I would say we keep this one open in case we can get a reproduction that scrolling doesn't work at all. And then use the other ticket for the incorrect scroll area issues.

**Comment by tomivirkki** [comment] 2021-05-04 08:21
> This issue is about not being able to scroll at all

See the attached video under "Live Demo" of the issue description. I think this is specifically about being able to scroll too far on Safari in case the columns overflow the viewport.

**Comment by mikaelliptak** [comment] 2021-05-04 08:48
Hello all,
the issue is not about, that user cannot scroll at all. The better issue description is, _the horizontal scroll area on iOS is  about double of what is actually needed by the columns._
It looks that solution of issue "Grid column width is calculated wrong on Safari 14.0.3 (Big Sur) #2177
" can resolved also our problem.

**Comment by sissbruecker** [comment] 2021-05-04 09:12
Yes the description was confusing me here, but your video likely demonstrates the same issue as in #2177.

**Comment by mikaelliptak** [comment] 2021-05-04 09:25
I apologize for confusing description.

**Comment by sissbruecker** [comment] 2021-05-06 07:42
@mikaelliptak Sorry to report that we will not be able to provide a fix for this. I'm repeating my comment [from here](https://github.com/vaadin/vaadin-grid/issues/2177#issuecomment-832767651):

> After discussing this internally we are going to close this as a won't fix.

> The issue happens due to the grids usage of `position: sticky` on the individual parts of the grid (header, body, footer) as part of its internal scroll mechanism, as well as the grid being placed into a flex container. Sticky positioning in flex containers works slightly different in Safari than it does in other browsers. That results in the sticky grid parts still being scrolled natively, in addition to the internal scrolling that the grid applies, thus scrolling the grid parts by double the amount that they should. That in turn leads to the grid showing an empty space for the amount of pixels that were scrolled additionally.

> The usage of `sticky` is part of the grids internal functionality that facilitates features like fixed columns, headers and footers, as well as synchronizing scrolling between all parts of the grid (header, body, footer) without a noticeable lag. As such it would be a considerable effort to move away from sticky positioning and it might degrade the other mentioned features for all users.

> In the future there might be a possibility that the Webkit team tackles the issues referenced below and aligns the sticky positioning behaviour with those of the other browsers.

> The only workaround ATM would be to not put the Grid into a Flex container, though this might be pretty difficult considering it's used heavily in our layout components and that the issue only occurs for Safari users. Using the workaround in the example above did improve things in my testing, but did not fix the issue completely.

> References:
> - [Webkit bug report 1](https://bugs.webkit.org/show_bug.cgi?id=175029), also includes a [comment](https://bugs.webkit.org/show_bug.cgi?id=175029#c3) explaining that this behaviour might be due to an unclear spec for sticky positioning
> - [Webkit bug report 2](https://bugs.webkit.org/show_bug.cgi?id=189461)
> - [Basic reproduction of the issue](https://jsbin.com/namagivoku/edit?html,output), open in Safari to see the element scrolling despite being sticky

**Closed by sissbruecker** 2021-05-06 07:42 UTC
Labels: Impact: High, Severity: Major
