### ISSUE TITLE
Blinking border regression in Safari

### ISSUE THREAD

**Issue by Saulis** [vaadin/vaadin-grid#853] opened 2017-04-20 10:14 UTC
![safari-regression](https://cloud.githubusercontent.com/assets/1039468/25225747/2eaeb2be-25cb-11e7-8926-cb5795a7da73.gif)

Introduced in c6a9e4d8, removing `style="bottom: 0` from the footer focus trap seems to help. The style is meant to make sure the focus trap element doesn't leak outside the table element which can be achieved with some other styles.

**Comment by jouni** [comment] 2017-04-20 11:06
As the original issue or the rows overlapping the top border is a Safari rendering bug, we should probably do a reduced test case and file a bug for webkit.

@tomivirkki, I remember you doing test cases earlier for this, would you happen to have those available still?

**Comment by tomivirkki** [comment] 2017-04-24 11:52
@Jouni Can’t reproduce it anymore. Looks like the original issue has been fixed in the newest version of Safari. Running the demos with a revision prior to https://github.com/vaadin/vaadin-grid/pull/709/commits/518165264f5d000623a7d106b48bc9fa567f2883 also seems to work now without the glitch we had before.

So the issue here is something new. Luckily it was simple to fix.

**Closed** 2017-04-25 07:48 UTC
Labels: bug, in review
