### ISSUE TITLE
[5.0-beta6] Weird issue with input text

### ISSUE THREAD

**Issue by yveslange** [vaadin/vaadin-grid#1260] opened 2018-03-22 15:06 UTC
### Description
When having lots of rows (few columns 7-8) and input text fields, while scrolling down it seems that the rows are not handling correctly. 
Eg: Edit the fields of the row index 0 (which is a the top). Scroll down 20-30 rows. Go back to the first row at the top. The input fields text changed, the text are the one from another row.

### Expected outcome
Scroll should not change the input text values.

### Actual outcome
Scrolling back and forward seems to change the values of the input text.

### Live Demo
![1](https://user-images.githubusercontent.com/17984393/37778375-1bce4178-2dea-11e8-9775-06df73e60346.PNG)
Here is the first row and in the second field I enter "test". Then I scroll down a bit (20-30 rows). 
![2](https://user-images.githubusercontent.com/17984393/37778464-4b2d26c8-2dea-11e8-81ff-0876aa1836a3.png)
Wooow... on another random row (index 35), the same field appears with the same value and it's also focused (i didn't clicked). And if you go at the top, the field is now "Some data" instead of "test"
![3](https://user-images.githubusercontent.com/17984393/37778668-cdd2512a-2dea-11e8-8c66-485fcb34ca2b.PNG)

### Steps to reproduce

1. Put a `vaadin-grid` element in the page.
2. Add a lot of rows (150) with <input type=text value="Some value">
3. Edit the first row (change the content to "test"
4. Scroll down
5. You might see your row somewhere else multiple times
6. Go back to the top.
7. sometime your edited row (at the top) is not there anymore.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by web-padawan** [comment] 2018-03-22 16:55
This looks as a duplicate of #1151, see also [1151#(comment)](https://github.com/vaadin/vaadin-grid/issues/1151#issuecomment-350982582)

**Comment by yveslange** [comment] 2018-03-23 08:35
Well, in my example there is no binding. Ok for #1151. 
For me this is not natural, logical and feels like a bug.

In pure javascript: if you generate multiple inputs (without bindings) in a `<div>` and you set the height of the div to have a scroll bar. If you edit the one field, it should not edit and focus another field that was generated.

**Comment by yveslange** [comment] 2018-03-23 08:44
I have create a function `_get(data, item, column.key)`. Each item that I have, has an unique identifier. Thus, I can retrieve the data using `item.id`. 

The issue is still there. 

What I don't understand is that this wasn't the case while using VaadinGrid 2, 3 or 4.

```
<template is="dom-repeat" items="[[_columns]]" as="column">
  <vaadin-grid-column>
    <template class="header">...</template>
    <template class="cell-content">
       <input type="text" value="[[_get(data, item, column.key]]">
    </template>
  </vaadin-grid-column>
</template>

**Comment by yveslange** [comment] 2018-03-27 10:57
Ok found why. This is because the underlying component doesn't bind the data to the one in the vaadin model. I'm using a staging area. The result is that vaadin re-render using the old data. Still strange that other fields are edited.

**Closed** 2018-03-27 15:24 UTC

**Comment by platosha** [comment] 2018-03-27 15:45
@yveslange the strange behavior of the input values does not seem to be a bug to me. There are many caveats here, so let me explain in steps.

Because of “virtual scrolling”, when input fields are used in the rows (or any other editable elements), you have to make sure their values are always two-way bound, so that:
- The inputs displays the correct values from your data set initially and after the scrolling
- They update your data set when user edits the input, so that your data set remains up-to-date, so that the correct value is restored from your data set after the user scrolls many rows away and back.

`[[item.value]]` is a one-way binding in Polymer. It does set the value of the input to the provided `item.value`, but does not update the `item.value` after the user edits in the input.

`{{item.value}}` is two-way, it should fix this issue in general, but there are some more caveats in your use case in particular.

First, the native `<input>` is not firing the change events in the manner that Polymer expects. The options are:
  - specify the update event name in the binding, e. g.: `{{item.value::input}}`, meaning update `item.value` when the `input` event is dispatched. This is what we use in the `<vaadin-grid>` two-way binding demo: https://cdn.vaadin.com/vaadin-grid/5.0.0-beta7/demo/#grid-basic-demos
  - alternatively, use `<iron-input>`: `<iron-input bind-value="{{item.value}}"></iron-input>`.

Second, it looks like your use case is more complicated than plain `item.value`, since you are using `<dom-repeat>` for columns and computed bindings for the input values, I mean `value=[[_get(...)]]`. Computed bindings are read-only by design, so the two-way binding syntax cannot be applied to them. The only option to handle the value edits in the input is to manually subscribe to the `input` events then:

```html
<template>
  <input
    type="text"
    value="_get(data, item, column.key)" 
    index="[[index]]"
    column-key="[[column.key]]"
    on-input="_onInput">
</template>

<script>
  // ...
    _onInput(event) {
      const input = event.target;
      // Plain JS: `this.data[input.index][input.columnKey] = input.value;`,
      // same in a Polymer data system way:
      this.set(['data', input.index, input.columnKey], input.value);
    }
</script>
```

The exact moment when the row data is swapped could change with the `<vaadin-grid>` version depending how optimal the grid code is. My guess, after recent optimisation changes in v5 beta, the number of physical number of rows in the DOM have decreased for you, and this is why the strange behavior did not occur in v2...v4.

Now, speaking about unexpected focus in the input after the user scrolls many rows away, this is a bug we indeed have in the grid, and this is reproducible in the Two-Way binding demo linked above.

**Comment by yveslange** [comment] 2018-03-28 13:41
Hi @platosha,

Thanks for the complete answer. Yes I understand and knows most of this. I said that it feels like a bug, I'm not saying that it's a bug ;). It's like going to the restaurant and ask for a salad. You might feel that it's not fresh but it's was cut the same morning as you are eating it. 

Thanks for the solution with on-input, this is a great a nice solution to manually sync the underlying data with the item that is stored in vaadin. I'll probably take your solution as it is. Didn't thought about it.

Another solution is to pass a callback to the component + the index + the data collection and let the component do the job (but this might be less efficient).

The focus issue is less important for me.

Thanks for your time ;)
