### ISSUE TITLE
Methods to allow manually setting certain rows of a grid to be unable to select

### ISSUE THREAD

**Issue by t0920008899** [vaadin/vaadin-grid#1840] opened 2020-05-20 08:37 UTC
in some scenario, we might need to manually set rows, which meet certain conditions, to be unable to get selected.

**Comment by TatuLund** [comment] 2020-10-12 09:54
Probably a duplicate of https://github.com/vaadin/vaadin-grid/issues/1180

**Comment by web-padawan** [comment] 2020-10-12 10:00
Thanks, this is indeed a duplicate of #1180. Closing.

**Closed by web-padawan** 2020-10-12 10:00 UTC
Labels: enhancement, vaadin-grid-flow
