### ISSUE TITLE
Question : How to handle items data binding with vaadin grid when using “Assigning Remote/Function Data” method

### ISSUE THREAD

**Issue by hyyan** [vaadin/vaadin-grid#1567] opened 2019-02-20 14:10 UTC
Hi, 
I am using the following example from vaadin docs with polymer3

```
<vaadin-grid id="grid" aria-label="Remote Data Example">
  <vaadin-grid-column path="firstName"></vaadin-grid-column>
  <vaadin-grid-column path="lastName"></vaadin-grid-column>
  <vaadin-grid-column path="email"></vaadin-grid-column>
</vaadin-grid>
<script>
  window.addEventListener('WebComponentsReady', function() {
    const grid = document.querySelector('vaadin-grid');

    grid.size = 200;
    grid.dataProvider = function(params, callback) {
      var xhr = new XMLHttpRequest();
      xhr.onload = function() {
        callback(JSON.parse(xhr.responseText).result);
      };
      var index = params.page * params.pageSize;
      xhr.open('GET', 'https://demo.vaadin.com/demo-data/1.0/people?index=' + index + '&count=' + params.pageSize, true);
      xhr.send();
    };
  });
</script>
```

Now how to update a row from the loaded items using polymer data binding

I have tried to access the items property in the grid using `this.$.grid.items` but this always returns the number of items

I want to be able to do something like `this.$.grid.items[0].firstName = 'changed'` and refelct the change into the grid

Any help is appreciated

**Note :** I have asked this question on [StackOverflow ](https://stackoverflow.com/questions/54762584/how-to-handle-items-data-binding-with-vaadin-grid-when-using-assigning-remote-f) but with no answer yet

**Comment by moderndeveloperllc** [comment] 2019-02-20 14:17
@hyyan You might get quicker answers for things like this from https://gitter.im/vaadin/web-components lots of Vaadin devs on there frequently, along with knowledgeable community users who would not be check issues on Github

**Comment by tomivirkki** [comment] 2019-02-20 15:04
Closing as a dupe of https://github.com/vaadin/vaadin-grid/issues/1526

**Closed by tomivirkki** 2019-02-20 15:04 UTC
