### ISSUE TITLE
Can't show column after hide

### ISSUE THREAD

**Issue by sithwin** [vaadin/vaadin-grid#525] opened 2016-11-10 07:41 UTC
I'm trying to show or hide column in vaadin-grid. After I hide a column, the column name doesn't display in vaadin-grid show / hide menu. Moreover, **hidden** column also doesn't display.

Here is my code:

 `<vaadin-grid #grid [items]="persons " >
	<table>
		<colgroup>
			<col name="id" hidable>
			<col name="name" hidable >
			<col name="birthday" hidden>
			<col name="department" >
			<col name="status" >
		</colgroup>
		<thead>
			<tr>
				<th>Id</th>
				<th>Name</th>
				<th>Birthday</th>
				<th>Department</th>
				<th>Status</th>
			</tr>
		</thead>
		</table>
</vaadin-grid>`

**Comment by Saulis** [comment] 2016-11-11 14:04
Hi!

I'm assuming you're trying to change the `hidden` status declaratively in the `<col>` element – unfortunately the `<table>` contents are pretty much readonly, so for any changes you need to access the column element using JS: `grid.columns[0].hidden = false;`

**Comment by sithwin** [comment] 2016-11-12 02:31
Here is the example from:
[vaadin-grid Column](https://cdn.vaadin.com/vaadin-core-elements/latest/vaadin-grid/demo/columns.html)

`<vaadin-grid>
  <table>
    <colgroup>
      <col>
      <col hidable="">
      <col hidable="" hidden="">
      <col hidden="">
    </colgroup>
    <thead>
      <tr>
        <th>Name</th>
        <th>Surname</th>
        <th>Team Activity</th>
        <th>Project Target</th>
      </tr>
    </thead>
  </table>
</vaadin-grid>`

I am using Angular2. How to use JS: `grid.columns[0].hidden = false;` in typescript.

Thanks.

**Comment by JimSangwine** [comment] 2016-11-29 07:55
@Saulis Actually this is affecting more people (myself included).

According to the [Vaadin Grid docs](https://vaadin.com/elements/-/element/vaadin-grid) you should be able to just add the "hidable" attribute to one or more columns like this:

    <vaadin-grid [items]="people" frozen-columns="2">
      <table>
        <colgroup>
          <col name="firstName">
          <col name="lastName">
          <col name="email" width="250">
          <col name="address.phone" hidable>
          <col name="address.street" hidable>
          <col name="address.city" hidable>
          <col name="address.state" hidable>
          <col name="address.zip" hidable>
          <col name="address.country" hidable hidden>
        </colgroup>
      </table>
    </vaadin-grid>

That works fine and the menu for showing and hiding columns appears, but the problem is when you hide one of the columns by clicking in the menu it disappears from the menu and so cannot be shown again.

**Comment by nicholaschantcs** [comment] 2017-01-13 13:03
Hey guys, it seems like this issue has not been resolved for quite some time now.
I just found out that on sidebar click, there a is `hidden` class( deselecting a row to show )added to the menu item of the side. By removing the `hidden` class, the hidden column name will then re-appear again.

I don't think there is an `hidable` event, as you can bypass this  by reseting the columns `hidable` and `hidden` with
```javascript
grid.columns[0].hidden = false
grid.columns[0].hidable = true
```


```HTML
<td class="gwt-MenuItem column-hiding-toggle hidden" id="gwt-uid-7" role="menuitem" colspan="2"><span class="v-off"><div>Title</div></span></td>
```

Possible fix:
I am not sure how it will work, but I am thinking changing the behaviour of the click button of the menuItem that doesn't include the `hidden` class should probably fix this issue.

```HTML
<td class="gwt-MenuItem column-hiding-toggle" id="gwt-uid-7" role="menuitem" colspan="2"><span class="v-off"><div>Title</div></span></td>
```

**Comment by tolgauen** [comment] 2017-02-03 13:59
I've come across this issue lately and I noticed like nicholaschantcs that a "hidden" class is added to the menu item. I'm using this classname as well to hide specific elements: 

`.hidden{
    display:none;
}` 

it looks like when the vaadin-grid menu item contains the hidden class, it picks up a "hidden" class which has been previously defined somewhere. The exact location of where it picks up the "hidden" class from can be found by inspecting the menu item with the hidden class.

**Comment by jouni** [comment] 2017-03-23 13:29
Duplicate of #197

**Closed by jouni** 2017-03-23 13:29 UTC
Labels: 1.x, bug
