### ISSUE TITLE
Dropdown content menus are clipped to cell

### ISSUE THREAD

**Issue by RebeccaStevens** [vaadin/vaadin-grid#842] opened 2017-04-03 06:09 UTC
When I try and put a paper-dropdown in a vaadin-grid-column to make that field editable, the dropdown content is clipped to the cell.
Is it possible to get the dropdown-content to display properly or is this a bug?

Gif showing the dropdown content being clipped:
![image](https://cloud.githubusercontent.com/assets/7224206/24597195/4a1fed0a-1898-11e7-8d9e-6f1f42020210.gif)

Code:
```html
<body>
  <template is="dom-bind" id="app">
    <vaadin-grid items="[[people]]">
      <vaadin-grid-column>
        <template class="header">Gender</template>
        <template>
          <paper-dropdown-menu label="Gender">
            <paper-listbox class="dropdown-content" attr-for-selected="gender" attr-for-item-title="gender" selected="{{item.gender}}">
              <template is="dom-repeat" items="[[genders]]" as="gender">
                <paper-item gender="[[gender]]">[[gender]]</paper-item>
              </template>
            </paper-listbox>
          </paper-dropdown-menu>
        </template>
      </vaadin-grid-column>
    </vaadin-grid>
  </template>
    
  <script>
    var app = document.querySelector("#app");
    
    app.people = [
      {
        name: "John",
        gender: "Male"
      }, {
        name: "Amy",
        gender: "Female"
      }, {
        name: "Owen",
        gender: "Gender Diverse"
      }
    ];
    
    app.genders = [
      "Male",
      "Female",
      "Gender Diverse"
    ];
  </script>
</body>
```

**Comment by Saulis** [comment] 2017-04-03 06:47
Hi @RebeccaStevens!

Unfortunately, this is a known issue which affects all list-like components that use row translating (`vaadin-grid`, `iron-list`, `iron-data-table`) when they are used together with `iron-dropdown` based components.

I've seen some workarounds like [this](https://github.com/PolymerElements/iron-list/issues/242#issuecomment-232450210), where you manually set `z-index` for the items.

If you are able to use `vaadin-combo-box` instead of `paper-dropdown-menu`, that will also get you out of trouble. 

On the bright side, we do have a plan and a working prototype on how to fix this clipping issue, which we'll probably continue working on right after the Polymer 2.0 support is out.

**Comment by tomivirkki** [comment] 2017-04-03 07:22
One workaround might also be to place the dropdown/editor outside the grid. On open you can position the overlay over the clicked cell if that’s how it should appear.

**Comment by RebeccaStevens** [comment] 2017-04-03 10:02
Thanks for the help :)

**Comment by stramel** [comment] 2017-04-06 03:17
Probably super hacky, but maybe it will help someone else who finds this.

```js
ready() {
        const el = this.$.groupList.$.scroller;
        el._positionItems = function() {
          this._adjustScrollPosition();
          var y = this._physicalTop;
          this._iterateItems(function(pidx, vidx) {
            this._physicalItems[pidx].style.transform = this._getTranslate(0, y);
            this._physicalItems[pidx].style.zIndex = this._physicalItems.length - pidx; // Sets the z-index to allow proper display
            y += this._physicalSizes[pidx];
          });
        }.bind(el);
      },
```

**Comment by guylhermetabosa** [comment] 2017-04-10 14:27
Any update on this?

**Comment by Saulis** [comment] 2017-04-13 06:13
@guylhermetabosa not at the moment, there's going to be a `2.1` release before we can start working on a fix for this.

**Comment by tomivirkki** [comment] 2017-04-13 06:56
The following fiddle demonstrates the issue in an isolated environment: https://jsfiddle.net/sf1may79/

As @Saulis mentioned, if the overlay (even a fixed one) is placed inside a layout that clips overflowing content, it will get cropped. There might be nothing we can do in the `<vaadin-grid>` itself to fix this `paper-dropdown` issue since we’ll need to use transforms (at least for the header/frozen/footer sections) anyway.

I also recommend trying `<vaadin-combo-box>` instead since it works around this by locating the overlay element right under the `<body>`.

**Comment by rajesh-sharma-0490** [comment] 2017-06-26 08:16
The same problem exists for vaadin-date-picker inside a vaadin-grid cell.
Has any fix been figured out yet ?

**Comment by jouni** [comment] 2018-01-08 08:46
> The same problem exists for vaadin-date-picker inside a vaadin-grid cell.
> Has any fix been figured out yet ?

Vaadin date picker recently adopted [`vaadin-overlay`](https://github.com/vaadin/vaadin-overlay), so it avoids this issue now. All Vaadin elements that have an overlay actually avoid this issue, so you are free to use them inside the rows.

I suppose we could introduce a `vaadin-tooltip` element since `paper-tooltip` suffers from this issue still.

@tomivirkki has a prototype hidden somewhere that replaces the current scroller implementation with a version that does not introduce this issue in the first place. I’m hoping we will see it eventually 😉

**Comment by tomivirkki** [comment] 2018-05-15 12:48
All Vaadin components with a dropdown/overlay now use `<vaadin-overlay>` internally so they should no longer clip. Closing.

**Closed by tomivirkki** 2018-05-15 12:48 UTC

**Comment by clivemo** [comment] 2018-10-09 10:39
We had a similar problem when we tried to show a custom "tooltip" in a grid, it got clipped or rather hidden by the rows underneath.
Simple solution for us was to add css for .v-grid-row :hover {z-index:1000;}

Not very scientific, but it might help someone :-)

/JC

**Comment by mihaisavezi** [comment] 2019-08-29 08:04
@clivemo There is no .v-grid-row class on anything in the vaadin-grid. What exactly did you style and if it's the vaadin-grid what is the version you were using ?

**Comment by clivemo** [comment] 2019-08-29 08:29
Vaadin 8

**Comment by mihaisavezi** [comment] 2019-08-29 08:33
Ok, so I guess your answer relates to the grid component in Vaadin for java, not the standalone web component

**Comment by clivemo** [comment] 2019-08-29 08:39
Yes it does, but my thought was that the general idea of changing z-index on row level might help someone.

**Comment by mihaisavezi** [comment] 2019-08-29 14:52
Tried something like changing the z-index for the tbody element. But this messes up scrolling visually. I guess the question is, is there a tooltip element that works inside vaadin-grid cells ?

**Comment by mihaisavezi** [comment] 2019-08-29 15:24
Ok, so it's because the stacking context issues caused by how scrolling is done. 

I see in the demo application, for something that's similar to a tooltip, a select-overlay, the element is created at the root level, and so there aren't any stacking context problems.

**Comment by mihaisavezi** [comment] 2019-08-30 10:44
For anyone still struggling with the stacking context issues, and that needs a tooltip that works with vaadin-grid, you can use tippy.js
