### ISSUE TITLE
GridPro "out of memory" on Firefox facing 1k Strings

### ISSUE THREAD

**Issue by unibe420** [vaadin/vaadin-grid#2195] opened 2021-09-21 08:05 UTC
### Description
Firefox shows "out of memory" when loading 1000 Strings in GridPro.
Chromium (Version 93.0.4577.82 (Official Build) snap (64-bit)) is able to show the 1000 Strings without errors.

Vaadin-bom Version 20.0.6, vaadin-grid-pro-flow Version 20.0.6.

### Expected outcome
The 1000 String are shown without errors.

### Actual outcome
"out of memory" in right corner of firefox.
Only 99 String shown and the other cells in the grid are empty.

### Steps to reproduce
``` 
public class Pair {
  String text;
  String type;
  
  public Pair(String text, String type) {
    this.text = text;
    this.type = type;
  }

  public String getText() {
    return text;
  }
}
```

```
public class MyGrid extends GridPro<Pair> {
  public MyGrid() {
    setWidth("100%");
    setHeightByRows(true);
    addColumn(Pair::getText);

    List<String> list = new ArrayList<>();
    for(int i=0; i<1000; i++) {
        list.add(new Pair(i+" some text", null));
    }

    ListDataProvider<Pair> dataProvider = new ListDataProvider<>(list);
    setItems(dataProvider);
  }
}
```

### Browsers Affected

- [ X] Firefox Mozilla Firefox 92.0

**Comment by unibe420** [comment] 2021-09-21 11:20
Thanks, solved the problem.

**Comment by web-padawan** [comment] 2021-09-21 11:23
See also [documentation](https://vaadin.com/docs/latest/ds/components/grid/#dynamic-height) for `setHeightByRows` which mentions this:

> In addition to setting any fixed or relative value, the height of a grid can be set by the number of items in the dataset, meaning that the grid will grow and shrink based on the row count.

> Please note that this disables scrolling and should not be used for large data sets to avoid performance issues.

Closing as the component works as intended.

**Closed by web-padawan** 2021-09-21 11:23 UTC
Labels: waiting for author
