### ISSUE TITLE
3.0beta1 Can't select text on rows when the column-reordering-allowed is true

### ISSUE THREAD

**Issue by bmodeprogrammer** [vaadin/vaadin-grid#912] opened 2017-06-23 10:32 UTC
I'm testing the new 3.0 beta1 and I can't select the text to have actions like copy/paste when the attribute of vaadin-grid is true.

This has workarounds? I found another [issue](https://github.com/vaadin/vaadin-grid/issues/316) related with this and had a workround but does not worked for me.

```
vaadin-grid {
    -moz-user-select: text;
    -webkit-user-select: text;
    -ms-user-select: text;
    user-select: text;
}
```

**Comment by web-padawan** [comment] 2020-02-20 11:44
There used to be such a problem in 3.x caused by these lines:

https://github.com/vaadin/vaadin-grid/blob/f5293a95e8926de4b916cf1d31ee7ff25cfcd0fe/vaadin-grid-table.html#L107-L113

![3 0](https://user-images.githubusercontent.com/10589913/74930460-51e88d80-53e6-11ea-9fa4-7cd737ece0f7.png)

Now in 5.x we don't have this problem anymore.

![5 0](https://user-images.githubusercontent.com/10589913/74930468-5a40c880-53e6-11ea-9d70-5548a227d7ef.png)


We no longer support `vaadin-grid` version 3, and now it is very outdated. Please consider using the most recent version (currently 5.x) which gets all the features and bug fixes. 

Closing as won't fix.

**Closed by web-padawan** 2020-02-20 11:44 UTC
Labels: 3.x, known issue
