### ISSUE TITLE
Old data is rendered if no new data is provided

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-grid#627] opened 2016-12-28 14:20 UTC
Tested using v2.0.0-pre.2

See https://jsfiddle.net/5jan63js/

When setting only 2 items and setting size to 100, the 2 items are not only rendered on rows 0 and 1, but also once more when you scroll down

**Comment by jouni** [comment] 2017-03-23 13:56
Still reproducible with the latest version (beta1). Scroll to row 500 and you see the data again: https://jsfiddle.net/exneb3gj/2/

**Comment by jouni** [comment] 2017-12-07 09:17
@tomivirkki, this is a duplicate of #1124

**Comment by tomivirkki** [comment] 2017-12-07 09:21
At least #1124 should now hide the rows with old data

**Closed by tomivirkki** 2017-12-07 09:21 UTC
