### ISSUE TITLE
Scrollbar visibility does not work properly when body has display:none initially

### ISSUE THREAD

**Issue by elmot** [vaadin/vaadin-grid#243] opened 2015-11-10 14:54 UTC
On windows, v-grid does not show a vertical scroll bar when the grid is initially rendered. If I scroll the grid using mouse wheel, the scrollbar appears, then disappears after some timeout. This behavior is very uncommon for windows users.

Win7/FF 38.4ESR: Appear/disappear bug, and scrollbar looks broken
Win7/Chrome 46: Appear/disappear bug
Win7/Opera 33: Appear/disappear bug, the scrollbar looks a bit strange(no right & top border)
Win7/IE 11: Vertical scrollbar is always visible, also unwanted horizontal scrollbar is shown.

See screenshots
![bug_v-grid_chrome_scrollbar](https://cloud.githubusercontent.com/assets/5366945/11065376/a8dc3452-87cb-11e5-96b0-2fd741686b91.png)
![bug_v-grid_ff_scrollbar](https://cloud.githubusercontent.com/assets/5366945/11065378/aaeda708-87cb-11e5-98fa-51ffdeee4cd1.png)
![bug_v-grid_ie_scrollbar](https://cloud.githubusercontent.com/assets/5366945/11065380/ad0efaaa-87cb-11e5-9d91-75ce8cb0324d.png)
![bug_v-grid_no_scrollbar](https://cloud.githubusercontent.com/assets/5366945/11065382/af8a4dac-87cb-11e5-9723-196fe339fa21.png)
![bug_v-grid_opera_scrollbar](https://cloud.githubusercontent.com/assets/5366945/11065384/b1125354-87cb-11e5-9029-438f9d694845.png)

**Comment by jounik** [comment] 2015-11-16 13:43
Most likely related: #191

**Comment by jounik** [comment] 2015-11-16 13:45
We need to investigate this more, seems that it affects more than just Windows. Timeboxed research for 1 person-day.

**Comment by jounik** [comment] 2015-11-20 12:19
Might be related: #30

**Comment by Saulis** [comment] 2015-11-23 12:51
@elmot which version of `<vaadin-grid>` are you using? Can you provide a JSFiddle or something where this occurs?

I tried to reproduce the issue on a Win7 VM running IE11, Chrome 46, FF42 with examples in our latest beta (https://cdn.vaadin.com/vaadin-elements/latest/vaadin-grid/demo/datasources.html) without "luck".

Tried also some older releases, but no cigar. If you have a new version of the `<vaadin-grid>` there problem might relate somehow to your application.

**Comment by Saulis** [comment] 2015-11-23 14:00
The problem seems to relate with how Grid is calculating the native scroll bar size. For some reason, the size in your app is calculated to be `0` which makes it behave like an `invisible` scrollbar. 

This issue might be related: https://dev.vaadin.com/ticket/14685

**Comment by Saulis** [comment] 2015-11-24 08:19
Conclusion:

When `Grid` is created, it tries to determine the size of the native scrollbars by temporarily attaching a `<div>` to the `<body>` and measuring the scrollbars from there. If the scrollbars are hidden during measuring, the size is set to be `0px` which in turn makes `Grid` assume that the scrollbars are to be shown only when scrolling and hidden otherwise.

In the application used by @elmot the `document.body` has `display:none` when the `Grid` is created which makes the scrollbar size to be measure at `0px`. The issue is not OS or Browser dependent, it happens with all combinations.

Workarounds for the application:
- Add CSS rule `visibility:visible !important;` for the scroller elements.
- Wrap the application inside a `<div>` and apply `display:none` to that element instead of `<body>` when loading.

For possible solutions, `Grid` should probably try to recalculate the native scrollbar size after it when it becomes visible.

[1]: https://github.com/vaadin/vaadin/blob/9c0eeb4b697ffa1db8f44a91724c9d612e4add50/client/src/com/vaadin/client/WidgetUtil.java#L411
[2]: https://github.com/vaadin/vaadin/blob/9c0eeb4b697ffa1db8f44a91724c9d612e4add50/client/src/com/vaadin/client/widget/escalator/ScrollbarBundle.java#L679
[3]: https://github.com/vaadin/vaadin/blob/9c0eeb4b697ffa1db8f44a91724c9d612e4add50/client/src/com/vaadin/client/widget/escalator/ScrollbarBundle.java#L501

**Comment by elmot** [comment] 2015-11-24 09:57
>Wrap the application inside a <div> and apply display:none to that element instead of <body> when loading.
Unfortunately this does not work. In my application there is no rule 
_body {display:none}_
, it has a rule
_body * {display:none}_
that means body itself is visible.

**Comment by Saulis** [comment] 2015-11-24 11:29
Oh that's right, `body *` will hit the child element that `Grid` uses when trying to measure the scrollbars. I'll update my previous message to reflect this.

**Comment by MartonEstok** [comment] 2016-11-22 17:30
I realize this is old, but I faced the same issue just now. My solution was to put the Grid in a `dom-if` and set the condition to true only when the host element got attached. The scrollbars appeared fine after.

**Comment by jouni** [comment] 2017-03-23 09:19
Thanks for the workaround @MartonEstok !

Wontfix for 1.x. The upcoming 2.0 version should not suffer from this issue.

**Closed by jouni** 2017-03-23 09:19 UTC
Labels: 1.x
