### ISSUE TITLE
Table rows and table resting the stacking context.

### ISSUE THREAD

**Issue by jvandervelden** [vaadin/vaadin-grid#877] opened 2017-05-15 13:40 UTC
The 'transform: translate()' on the table rows is creating new stacking contexts. This is causing issues with any element that is floating like the polymer drop down menu element (illustrated below) and the vaadin context menu.

![image](https://cloud.githubusercontent.com/assets/7331813/26059919/6657f0b0-3951-11e7-971e-4bde6083019e.png)

The subsequent rows are over the drop down list because the stacking context is at the row level, so the drop down menu's z-index is only functional against the items in it's table row.

If transform is changed to the top css style, the stacking context isn't broken and does the same thing as transform:

![image](https://cloud.githubusercontent.com/assets/7331813/26060028/d763a204-3951-11e7-9a6a-846dd0542e87.png).

**Comment by jouni** [comment] 2017-05-15 15:40
This is a well known issue, duplicate of #842. We have one prototype how to fix this but it will take some heavier refactoring and probably won’t happen in the near future. In the meantime, you can try a native select element or vaadin-combo-box instead for the dropdown menus.

**Comment by jouni** [comment] 2017-05-15 15:41
One more note: changing from `transform` to `top` would cause a major rendering performance regression on slower devices, and isn’t considered a viable solution by the team.

**Closed by jouni** 2017-05-15 15:40 UTC

**Comment by jvandervelden** [comment] 2017-05-15 16:56
Thanks for the information. Vaadin combo box looks like it will work for us.
