### ISSUE TITLE
Styling active-cells using custom templates

### ISSUE THREAD

**Issue by sarahspencer** [vaadin/vaadin-grid#1343] opened 2018-08-02 15:36 UTC
### Description
How do I style active-cells (and subsequently the entire row of active cells)?

### Expected outcome

Previously, using mixins, Vaadin provided the ability to style both "active" and "selected" cells. 

(My vaadin-grid has a selection column)
When the user clicks anywhere on a row (not a checkbox), the entire row becomes a row of "active" cells and has the styling associated with active-cell. 

When the user clicks on a checkbox, the entire row becomes a row of "selected" cells and has the styling associated with selected-cell. 

Ex:
--vaadin-grid-body-row-active-cell: {
     background: #535353;
}; 
--vaadin-grid-body-row-selected-cell: {
     background: #424242;
};

### Actual outcome

Using the newer method of vaadin-grid styling with custom templates, I can't figure out how to style "active" items...I don't see any related state attributes in the API docs.

I am able to style the "selected" row using:
[part="row"][selected] {
    background: #424242;
} 

The good news is selection using active-item is working. Functionally, my grid remains consistent for passing this data from the row when I simply click in the row (not the checkbox). 
But I can't style the active row. 

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by web-padawan** [comment] 2018-08-02 17:29
Thanks for the issue. This is a duplicate of #1205 so closing in favour of that, and moved that issue higher in our list. We might consider shipping this feature in one of the upcoming minor releases.

**Closed by web-padawan** 2018-08-02 17:29 UTC
