### ISSUE TITLE
Vaadin Grid header alignment and scrollbar behavior in right-to-left layout (RTL)

### ISSUE THREAD

**Issue by mahmoodsalamah23** [vaadin/vaadin-grid#1472] opened 2018-10-19 20:06 UTC
### Description

I am using vaadin-grid in a Polymer 2.0 application. The application is in Arabic and is having an RTL direction. The drection: rtl CSS property is set at the HTML and BODY element levels.

![grid header problems](https://user-images.githubusercontent.com/29669411/47241036-ead25780-d3f2-11e8-912e-ff158caf9c3d.gif)

### Expected outcome

The grid should shift the direction of columns as well as the default alignment for headers and contents to be right-aligned.

### Actual outcome

The actual result is showing three problems as illustrated in the attached animated GIF image. The first problem is that the header of the column is having right white space that I think was reserved for the scrollbar. The second problem is that the grid shows a horizontal scrollbar despite having a single single column. The third problem is that whenever the vertical scrollbar is scrolled (up or down it does not matter), the horizontal scrollbar always scrolls left.

**Note**: The header text get properly aligned when using the vertical scrollbar. At the same time, rows get aligned out of the grid.

### Steps to reproduce

1- Put a vaadin-grid element in an application and have it bind to an Array.
2- Setup the columns
3- Change the direction of the HTML and BODY tags to be RTL;
4- Notice the described problems.

### Browsers Affected

This application is still in early development stages and is currently being tested in Chrome only.

**Comment by fadinemer** [comment] 2018-11-06 10:41
This is really needed. It is killing me too.

**Comment by tomivirkki** [comment] 2018-11-13 10:05
Thanks for reporting. Created this epic for known rtl-specific issues in the grid: https://github.com/vaadin/vaadin-grid/issues/1490

**Comment by mahmoodsalamah23** [comment] 2019-03-24 07:46
@tomivirkki 

Are there any plans on fixing the above reported issue? It is really leaving our project, which is due for delivery by mid July 2019. 

Many Thanks for your support.

**Comment by tomivirkki** [comment] 2019-03-28 16:00
Hi @mahmoodsalamah23 Thanks for your patience. I took a look to the issues. Tested the newest grid release on the newest Chrome by adding `<html dir="rtl">` to the demo page at https://cdn.vaadin.com/vaadin-grid/5.3.3/demo/#grid-columns-demos

Issue 1:
> The first problem is that the header of the column is having right white space that I think was reserved for the scrollbar. 

Couldn't reproduce this. Here's my screen recording:

![issue-1](https://user-images.githubusercontent.com/1222264/55172637-051f1700-5183-11e9-9327-99907556ecc0.gif)


Issue 2:
> The second problem is that the grid shows a horizontal scrollbar despite having a single single column.

Removed all columns but one from the demo and let it span full-width of the grid. Couldn't reproduce the issue. Here's the screen recording:

![issue-2](https://user-images.githubusercontent.com/1222264/55172658-0c462500-5183-11e9-885e-f7aaa97d307a.gif)


Issue 3:
>The third problem is that whenever the vertical scrollbar is scrolled (up or down it does not matter), the horizontal scrollbar always scrolls left.

This one I could reproduce and it seems to be bothering ltr also. The keyboard navigation mixin tries to `focus()` a cell from the grid that's out of the current viewport on `focusin` event. Since keyboard focus doesn't work too well with rtl either, you could prevent this from happening with the following workaround:

`grid.addEventListener('focusin', e => e.stopImmediatePropagation(), true);`

**Comment by tomivirkki** [comment] 2020-10-16 12:34
Closing, official RTL support added in Vaadin 16 https://vaadin.com/releases/vaadin-16#rtl

**Closed by tomivirkki** 2020-10-16 12:34 UTC
Labels: RTL
