### ISSUE TITLE
TreeGrid no custom header in selection column 

### ISSUE THREAD

**Issue by xdenser** [vaadin/vaadin-grid#2066] opened 2020-10-23 09:41 UTC
### Description
I am unable to render anything in selection column header, neither header nor headerRenderer work, the renderer is called but I get empty header no matter what I put in passed header cell element. 
For other columns header renderers work for me.

I use v5.6.6

**Comment by DiegoCardoso** [comment] 2020-10-28 10:14
Hi @xdenser,

Could you please attach a small project where we can verify this issue? I tried locally, but wasn't able to reproduce it.

Thanks in advance.

**Comment by xdenser** [comment] 2020-10-29 09:23
Sorry. Header attribute works in the end but headerRenderer does not.  See example project. I use data provider in my project, but it does not work even with flat items.
[vaadin-grid-issue2066.zip](https://github.com/vaadin/vaadin-grid/files/5457298/vaadin-grid-issue2066.zip)

**Comment by DiegoCardoso** [comment] 2020-11-04 10:25
Thanks for the project and sorry for the delay on response.

I could verify it and it seems to behave differently for a Lit project. For the columns, we offer the options to either use a renderer function or a template for the parts. But, selection column is a special case, because it has its own template, so to allow it to be customized, it checks and cleans the cell to use the header renderer instead, when there's one. But for some reason that needs further investigation, as it seems from your sample project, while using it with Lit, the code that cleans the cell is being called more often and some calls are done after the last call to renderer happens, therefore leaving the cell blank.

I found a way to workaround this, which consists on calling the `render` function within a `requestAnimationFrame` callback in order to delay the stamp of the cell content. I couldn't verify if it might bring any other undesired behavior.

**Comment by web-padawan** [comment] 2021-05-17 12:33
Closing in favor of https://github.com/vaadin/web-components/issues/400 where the underlying problem is reported.

**Closed by web-padawan** 2021-05-17 12:33 UTC
Labels: Impact: Low, Severity: Minor, bug

**Comment by tomivirkki** [comment] 2021-05-17 12:37
Note that Flow grid doesn't use the `<vaadin-grid-selection-column>` but it defines its [own Web Component](https://github.com/vaadin/flow-components/blob/master/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/vaadin-grid-flow-selection-column.js) for the purpose
