### ISSUE TITLE
4.0.0-alpha2 - Row render issue

### ISSUE THREAD

**Issue by moderndeveloperllc** [vaadin/vaadin-grid#1011] opened 2017-09-26 16:51 UTC
There seems to be an issue with the newest alpha when it comes to first-time row rendering for rows that are not on screen in the first paint. it can also show if you assign `items` a second time to the grid.

Example: https://jsbin.com/gutefop/edit?html,console,output

Scroll all the way to the bottom quickly on first load and you can see it. Wait 3 seconds and the reassign will show the problem too. Attached is a screenshot of what I see on Safari. This was not an issue with 3.0.2.
<img width="678" alt="gridalpharendering" src="https://user-images.githubusercontent.com/1920405/30872817-f53bf808-a2b0-11e7-9c44-0199031ca0a3.png">

**Comment by tomivirkki** [comment] 2017-09-26 18:02
Thanks for reporting. Reverted some code that was badly cleaned up. Does the latest master work for you now?

**Comment by moderndeveloperllc** [comment] 2017-09-26 18:08
@tomivirkki `master` looks good. If you are looking at this now, you might want to check how the grid determines its width. I'm getting horizontal scrollbars on the jsbin and my code no matter how wide I make the grid - even well past the content length.

**Comment by tomivirkki** [comment] 2017-09-26 18:11
Yeah, probably caused by https://github.com/vaadin/vaadin-grid/issues/1006

**Comment by tomivirkki** [comment] 2017-09-28 11:08
Closing this issue. Also, fix for #1006 is in review

**Closed by tomivirkki** 2017-09-28 11:08 UTC
