### ISSUE TITLE
Need scrolling to item support

### ISSUE THREAD

**Issue by Waynezhi** [vaadin/vaadin-grid#1274] opened 2018-04-12 10:09 UTC
### Description

After adding a item to grid, we need to highlight this new item, or scroll to any specific item by a simple match.

could be possible to support this feature ?

**Comment by tomivirkki** [comment] 2018-04-12 10:12
Duplicate of https://github.com/vaadin/vaadin-grid/issues/1154

Also see https://github.com/vaadin/vaadin-grid/issues/1169

**Closed by tomivirkki** 2018-04-12 10:12 UTC
