### ISSUE TITLE
Should sorting path be a property on <vaadin-grid-column>

### ISSUE THREAD

**Issue by vaadin-marcus** [vaadin/vaadin-grid#769] opened 2017-03-03 17:23 UTC
Why is it that we need to define a <vaadin-grid-sorter> element for sorting and not setting a property on the column like for resizing/reordering? Feels a bit inconsistent.

Without reading docs my intuition would have been to use something like `<vaadin-grid-column sort-by="item.user.name.last" resizable> </vaadin-grid-column>`

**Comment by tomivirkki** [comment] 2017-03-04 09:16
This is similar to https://github.com/vaadin/vaadin-grid/issues/492

**Comment by jouni** [comment] 2017-03-23 06:58
I would say this is a duplicate of #492.

**Closed by jouni** 2017-03-23 06:58 UTC
Labels: 2.0, enhancement
