### ISSUE TITLE
feature request: scrollTo(T item)

### ISSUE THREAD

**Issue by gsedlacz** [vaadin/vaadin-grid#1876] opened 2020-03-09 12:43 UTC
It would be much appreciated to have method that scrolls to a certain item.

```
public class Grid<T> ... {
    public void scrollTo(T item) {
        ...
    }
}
```

My current workaround involves both the current filter (`SerializablePredicate<T>`) and the Grids `DataCommunicator`. This type of problem should be solved by the `Grid`s API itself.

**Comment by web-padawan** [comment] 2020-10-12 19:21
Closing as duplicate of #1154

**Closed by web-padawan** 2020-10-12 19:21 UTC
Labels: vaadin-grid-flow
