### ISSUE TITLE
Grid: AppendFooterRow produces an Error when appending more than 8 FooterRows

### ISSUE THREAD

**Issue by chandmichael** [vaadin/vaadin-grid#2140] opened 2021-03-03 11:40 UTC
### Description
If I append more than 8 footer rows, the error message "TypeError: Cannot read property 'pop' of null" is being displayed and the order of the cells is incorrect

### Expected outcome
Footer rows are appended and displayed as expected

### Actual outcome
ErrorMessage is being displayed an the order of the cells is incorrect

### If you only append 8 footer rows it works fine
```
public class MyGrid extends Grid<Object> {

	public MyGrid () {
		addColumn(t -> "1").setKey("1");
		addColumn(t -> "2").setKey("2");

		IntStream.range(0, 9).forEach(i -> appendFooterRow());
	}
}
```

**Comment by web-padawan** [comment] 2021-03-03 13:22
Closing as duplicate of https://github.com/vaadin/vaadin-grid/issues/1556, as the root cause is the same.

**Closed by web-padawan** 2021-03-03 13:22 UTC
