### ISSUE TITLE
Vaadin-Grid exception on version 1.2.0

### ISSUE THREAD

**Issue by toshovski** [vaadin/vaadin-grid#562] opened 2016-12-09 18:45 UTC
When I use the templatizer together with vaadin-grid I get an exception in the vaadin-grid. The method refreshItems clears the selection on page load and the selection is undefined: See the refreshItems function line 1460.

`Uncaught TypeError: Cannot read property 'clear' of undefined
    at HTMLElement.refreshItems (vaadin-grid.html:1460)
    at HTMLElement._itemsChanged (vaadin-grid.html:1225)
    at HTMLElement._complexObserverEffect (polymer.html:1654)
    at HTMLElement._effectEffects (polymer.html:1489)
    at HTMLElement._propertySetter (polymer.html:1473)
    at HTMLElement.setter (polymer.html:1552)
    at HTMLElement.refreshTable (abas-table.html:85)
    at HTMLElement._complexObserverEffect (polymer.html:1654)
    at HTMLElement._effectEffects (polymer.html:1489)
    at HTMLElement._propertySetter (polymer.html:1473)
    at HTMLElement.__setProperty (polymer.html:1482)
    at HTMLElement._applyConfig (polymer.html:2092)
    at HTMLElement._afterClientsReady (polymer.html:2086)
    at HTMLElement._ready (polymer-mini.html:74)
    at TemplateInstance._readyClients (polymer-mini.html:82)
    at TemplateInstance._ready (polymer-mini.html:70)
    at TemplateInstance._tryReady (polymer-mini.html:60)
    at TemplateInstance._constructorImpl (polymer.html:4454)
    at new TemplateInstance (polymer.html:4259)
    at HTMLElement.stamp (polymer.html:4483)
    at HTMLElement.doTemplatization (abas-fragment-behavior.html:72)
    at HTMLElement.handleGetScreenResponse (abas-fragment.html:63)
    at HTMLElement.handler (polymer.html:561)
    at HTMLElement.fire (polymer.html:1327)
    at HTMLElement._handleResponse (iron-ajax.html:479)
refreshItems @ vaadin-grid.html:1460
_itemsChanged @ vaadin-grid.html:1225
_complexObserverEffect @ polymer.html:1654
_effectEffects @ polymer.html:1489
_propertySetter @ polymer.html:1473
setter @ polymer.html:1552
refreshTable @ abas-table.html:85
_complexObserverEffect @ polymer.html:1654
_effectEffects @ polymer.html:1489
_propertySetter @ polymer.html:1473
__setProperty @ polymer.html:1482
_applyConfig @ polymer.html:2092
_afterClientsReady @ polymer.html:2086
_ready @ polymer-mini.html:74
_readyClients @ polymer-mini.html:82
_ready @ polymer-mini.html:70
_tryReady @ polymer-mini.html:60
_constructorImpl @ polymer.html:4454
TemplateInstance @ polymer.html:4259
stamp @ polymer.html:4483
doTemplatization @ fragment-behavior.html:72
handleGetResponse @ fragment.html:63
handler @ polymer.html:561
fire @ polymer.html:1327
_handleResponse @ iron-ajax.html:479`

the beta version works fine

**Comment by Saulis** [comment] 2016-12-22 09:56
Hi!

Would you be able to provide a code snippet where we could try to reproduce the issue? Thanks!

**Comment by platosha** [comment] 2017-05-26 12:55
Closing due to unable to reproduce.

Please consider upgrading to `<vaadin-grid>` v2.0 or later.

**Closed by platosha** 2017-05-26 12:55 UTC
Labels: 1.x
