### ISSUE TITLE
Scrollbars only for the second grid in Chrome

### ISSUE THREAD

**Issue by ccschneidr** [vaadin/vaadin-grid#395] opened 2016-06-27 08:41 UTC
If you open the headers.html (1.0, 1.1 beta4 or master) demos and scroll to the bottom you can see scrollbars in the "Auto generated header text" demo. However, if you remove all the demos but the named one Chrome 51 does not show the scrollbars any more. If you re-add another (empty) vaadin-grid before that demo scrollbars show up again. (In IE 11 everything works as expected.)

**Comment by manolo** [comment] 2016-07-12 20:42
@ccschneidr What is your OS and its version ?

**Comment by ccschneidr** [comment] 2016-07-13 06:58
Windows 7 Enterprise SP1

**Comment by manolo** [comment] 2016-07-13 09:42
Alright, seems a problem in the component when computing sizes and whether the synthetic scroll blocks should be shown.

It's not reproducible in mac unless you connect a mouse and configure `Show scroll bars: Automatically based on mouse or trackpad` because chrome in mac reports a weight of zero when scrollbars are show only on scrolling.

**Comment by jouni** [comment] 2017-03-23 12:31
Wontfix for 1.x. The upcoming 2.0 version (now in beta) should not have this issue. Please upgrade to that if at all possible. Thanks!

**Closed by jouni** 2017-03-23 12:31 UTC
Labels: 1.x
