### ISSUE TITLE
Strange behaviour with opened console

### ISSUE THREAD

**Issue by YuriyVaadin** [vaadin/vaadin-grid#1380] opened 2018-08-29 14:27 UTC
### Description
The body cells are not rendered when console is opened (99% of cases)

### Expected outcome
The body cells are rendered.

### Actual outcome
The body cells are not rendered. 

### Live Demo
https://cdn.vaadin.com/vaadin-grid/5.2.0-alpha1/demo/#grid-basic-demos (Content Renderer Function)

![grid-bug](https://user-images.githubusercontent.com/29372419/44794216-b1c6f500-abb0-11e8-887e-5a036e75c083.gif)

### Steps to reproduce
1. Open demo page.
2. Open developer console
3. Reload the page several times

### Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by limonte** [comment] 2018-09-03 09:25
Duplicate of #1168

`<iron-ajax>` seems to be unreliable.

**Closed by limonte** 2018-09-03 09:25 UTC
