### ISSUE TITLE
<v-grid> then() doesn't wait for automatic row height detection on load

### ISSUE THREAD

**Issue by Saulis** [vaadin/vaadin-grid#19] opened 2015-06-05 08:40 UTC
Given a `<v-grid>` with `display: none` 

``` html
<v-grid style='display: none'>
  <table>
    <col header-text='Name'>
    <tr>
      <td>Grid</td>
    </tr>
   </table>
</v-grid>
```

Calling 

``` js
grid.then(function() {
  grid.style.display = 'block';
});
```

right after loading the component will occasionally result in a race condition with the automatic row height detection and the grid height will be 1px \* number of rows.

`grid.then` should wait for the row height detection so that we could safely modify the `display` attribute.

As a workaround, `setTimeout` with `500ms` seems to work.

**Comment by manolo** [comment] 2015-06-05 09:00
then relies in vaadin grid isWorkingPending, but there are many cases not handled by that.

**Comment by Saulis** [comment] 2015-06-05 13:07
@manolo yes, in this case I believe the `autodetectRowHeightLater` in [Escalator.java](https://github.com/vaadin/components/blob/794016f1c2864688a2ac460b0ef6c92b206d6045/vaadin-components-gwt/src/main/java/com/vaadin/client/widgets/Escalator.java#L1748)

**Comment by manolo** [comment] 2015-06-08 05:45
Yes that should be included somehow, but I'm not entirely it is enough, we should check all Scheduler or Timers and use flags or maybe `SchedulerImpl.isWorkQueued` to be absolutely sure that nothing is pending.

**Comment by amahdy** [comment] 2015-08-13 10:21
Unable to reproduce. Can you please provide example code, browser version, ...etc?

Also we started to use more reliable function `HTMLImports.whenReady()` instead of `grid.then()` and `setTimeout`.

**Comment by tomivirkki** [comment] 2015-08-13 10:27
HTMLImports.whenReady invokes when the html imports on the page are ready.
grid.then on the other hand returns a Promise that resolves when all necessary processes of an individual v-grid are completed so they're meant for different things.

**Comment by Saulis** [comment] 2015-10-13 08:21
This test from `grid-resizing.html` ('should work if originally invisible') should work without the `setTimeout()` 

```js
          // Using onRegister because in FF the new grid takes a while to be initialized
          onRegister(grid, function() {
            expect(grid.offsetHeight).to.equal(0);

            //TODO: timeout here because of https://github.com/vaadin/components/issues/19
            grid.then(function() {
              setTimeout(function() {
                grid.removeAttribute("style");
                grid.then(function() {
                  expect(grid.offsetHeight).to.be.at.least(30);
                  wrapper.removeChild(tmp);
                  done();
                });
              }, 100);
            });
          });
```

**Comment by manolo** [comment] 2015-10-14 11:11
We had to modify this test as well (grid-resizing.html)

        it('should resize with a details row open', function(done) {
          grid.rowDetailsGenerator = function() {
            return document.createElement("input");
          }
          var originalHeight;

          grid.then(function() {
            grid.setRowDetailsVisible(0, true);
            return grid;
          }).then(function() {
            originalHeight = grid.clientHeight;
            grid.style.height = "100px";
            
            // Using waitUntil instead of chaining grid.then because 'onresize' event from
            // iframe is not asynchronous (very noticeable in android 5.x emulator)
            // Related with : https://github.com/vaadin/vaadin-grid/issues/19
            waitUntil(function(){
              return originalHeight != grid.clientHeight;
            }, function(){
              grid.style.height = "";
              waitUntil(function(){
                return originalHeight == grid.clientHeight;
              }, done, done);
            }, done);
          });
        });

**Comment by jouni** [comment] 2017-03-23 08:44
Wontfix

**Closed by jouni** 2017-03-23 08:44 UTC
Labels: 1.x
