### ISSUE TITLE
Integration tests on local machine fail due to hardcoded port

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/vaadin-grid#1909] opened 2019-11-07 09:33 UTC
The IT basic class `AbstractNoW3c` uses the `RemoteWebDriver` initialized with the value returned from `getHubUrl()`. When not configured for sauce labs, the returned url maps automatically to port 4444.

The tests are run with 
`mvn install verify -Plocal-run - Dwebdriver.chrome.driver=C:/drivers/chromedriver.exe`

This leads to error messages like:
```
[ERROR] doubleClickDetailsCell_noItemClickEventFired[ANY_Chrome_](com.vaadin.flow.component.grid.it.ItemClickListenerIT)  Time elapsed: 2.041 s  <<< ERROR!
org.openqa.selenium.remote.UnreachableBrowserException: 
Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: '<your_machine_name>', ip: '<your_ip>', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
Driver info: driver.version: RemoteWebDriver
Caused by: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:4444
Caused by: java.net.ConnectException: Connection refused: connect
```

After replacing the `RemoteWebDriver` with `ChromeDriver` the tests are running perfectly.

-> 
```
public class AbstractNoW3c extends AbstractComponentIT {
    public void setup() throws Exception {
            // ...
            WebDriver driver = TestBench.createDriver(new ChromeDriver(options));
            // ...
    }
}
```

AbstractNoW3c should use the simple Chrome Driver when running with maven profile `local-run`.

**Comment by web-padawan** [comment] 2020-10-06 18:28
The Flow components are now moved to the monorepo. Closing, please create a new issue if the problem is still valid.

**Closed by web-padawan** 2020-10-06 18:28 UTC
Labels: vaadin-grid-flow
