### ISSUE TITLE
Grid.getDataProvider().refreshAll() length must not be negative

### ISSUE THREAD

**Issue by ziza** [vaadin/vaadin-grid#2128] opened 2021-02-03 16:33 UTC
Vaadin 18.0.5
Vaadin 19.0.0.alpha5

After scrolling several records in the grid and then calling "getDataPovider().refreshAll" with a filter that does not return any data, the following exception is thrown:
`java.lang.IllegalArgumentException: length must not be negative`
`	at com.vaadin.flow.internal.Range.withLength(Range.java:131) ~[flow-server-6.0.0.alpha5.jar:6.0.0.alpha5]`
`	at com.vaadin.flow.data.provider.DataCommunicator.flush(DataCommunicator.java:1088) ~[flow-data-`6.0.0.alpha5.jar:6.0.0.alpha5]`

### Steps to reproduce
1. Run attached example.
2. Scroll until you see at least 500 records.
3. Type in the filter field "x" or any other term that does not match any record.
4. The exception is thrown.

Tested on chrome

[log.txt](https://github.com/vaadin/vaadin-grid/files/5919997/log.txt)
[my-project.zip](https://github.com/vaadin/vaadin-grid/files/5919998/my-project.zip)

![a4da867d5d294c01b930e62bff802bb5](https://user-images.githubusercontent.com/49871294/107049957-79786780-67a9-11eb-92f1-a4468b8dfbae.gif)

**Comment by yuriy-fix** [comment] 2021-02-10 15:14
The issue is caused by https://github.com/vaadin/flow/issues/9988.
Closing as a duplicate.

**Closed by yuriy-fix** 2021-02-10 15:14 UTC
