### ISSUE TITLE
@type annotations for function appear to be invalid

### ISSUE THREAD

**Issue by achernya** [vaadin/vaadin-grid#483] opened 2016-10-10 21:46 UTC
It looks like the `@type` annotations used for function are not valid Closure annotations, resulting in the following errors:

1x:
WARNING - Bad type annotation. missing opening ( See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.
       \* @type {(Array<Object>|function)}
3x:
WARNING - Bad type annotation. missing opening ( See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.
     \* @type {function}

Specifying the full function type should correct these issues.

**Comment by Saulis** [comment] 2016-11-11 13:50
Hi!

I think the problem is fixed by just using `Function` instead of `function` – can you try out how the branch `fix-annotations` works for you? Thanks!

**Closed** 2016-11-18 07:03 UTC
Labels: in review
