### ISSUE TITLE
Unable to download vaadin-grid

### ISSUE THREAD

**Issue by jaipsah** [vaadin/vaadin-grid#1181] opened 2018-01-13 16:14 UTC
### Description

I tried to install vaadin-grid and some package is not found. So, i am unable to install it.

when i executed this command `bower install --save vaadin/vaadin-grid`  

this error happend:   

> PS D:\Projects\test-polymer> bower install --save vaadin/vaadin-grid
bower vaadin-grid#*             cached https://github.com/vaadin/vaadin-grid.git#4.1.0
bower vaadin-grid#*           validate 4.1.0 against https://github.com/vaadin/vaadin-grid.git#*
bower web-component-tester#^6.4.1           cached https://github.com/Polymer/web-component-tester.git#6.4.3
bower web-component-tester#^6.4.1         validate 6.4.3 against https://github.com/Polymer/web-component-tester.git#^6.4.1
bower vaadin-text-field#^1.0.0              cached https://github.com/vaadin/vaadin-text-field.git#1.2.0
bower vaadin-text-field#^1.0.0            validate 1.2.0 against https://github.com/vaadin/vaadin-text-field.git#^1.0.0
bower vaadin-checkbox#^1.0.0             ENOTFOUND Package vaadin-checkbox not found    

Please suggest.

**Comment by web-padawan** [comment] 2018-01-13 17:40
@jaipsah could you please run `bower cache clean` and then try to install `vaadin-checkbox` itself? The package exists, and I cannot reproduce the problem now, so I suppose it was occasional GitHub failure.

**Comment by jaipsah** [comment] 2018-01-13 18:23
@web-padawan i tried what you suggested but still there are some issues:  

>PS D:\Projects\test-polymer> bower install --save vaadin/vaadin-checkbox
bower vaadin-checkbox#*         cached https://github.com/vaadin/vaadin-checkbox.git#1.0.3
bower vaadin-checkbox#*       validate 1.0.3 against https://github.com/vaadin/vaadin-checkbox.git#*
bower web-component-tester#^6.4.1           cached https://github.com/Polymer/web-component-tester.git#6.4.3
bower web-component-tester#^6.4.1         validate 6.4.3 against https://github.com/Polymer/web-component-tester.git#^6.4.1
bower                                        retry Request to https://raw.githubusercontent.com/bower/components/master/packages/vaadin-control-state-mixin failed with ETIMEDOUT, retrying in 1.9s
bower vaadin-control-state-mixin#^1.0.0  ENOTFOUND Package vaadin-control-state-mixin not found


i have added the **`bower.json`** file. Is there any issue with the installations.  

```
{
  "name": "polymer-starter-kit",
  "authors": [
    "The Polymer Authors"
  ],
  "license": "https://polymer.github.io/LICENSE.txt",
  "dependencies": {
    "app-layout": "PolymerElements/app-layout#^2.0.0",
    "app-route": "PolymerElements/app-route#^2.0.0",
    "iron-flex-layout": "PolymerElements/iron-flex-layout#^2.0.0",
    "iron-iconset-svg": "^2.1.0",
    "iron-media-query": "PolymerElements/iron-media-query#^2.0.0",
    "iron-pages": "PolymerElements/iron-pages#^2.0.0",
    "iron-selector": "PolymerElements/iron-selector#^2.0.0",
    "paper-icon-button": "PolymerElements/paper-icon-button#^2.0.0",
    "polymer": "Polymer/polymer#^2.0.0",
    "webcomponentsjs": "webcomponents/webcomponentsjs#^1.0.0",
    "paper-input": "^2.0.5",
    "paper-button": "^2.0.0",
    "iron-icons": "^2.0.1",
    "iron-ajax": "polymerelements/iron-ajax#^2.0.6",
    "paper-dialog": "^2.0.1",
    "paper-fab": "^2.0.0",
    "paper-spinner": "^2.0.0",
    "paper-tooltip": "^2.0.1",
    "iron-form": "^2.0.1",
    "materialize": "^0.100.2",
    "web-component-tester": "Polymer/web-component-tester#^6.4.1",
    "vaadin-themable-mixin": "vaadin/vaadin-themable-mixin#^1.1.5",
    "vaadin-control-state-mixin": "vaadin/vaadin-control-state-mixin#^2.0.2"
  },
  "resolutions": {
    "polymer": "^2.0.0"
  },
  "devDependencies": {
    "web-component-tester": "^6.4.1"
  },
  "private": true
}

```

**Comment by web-padawan** [comment] 2018-01-15 08:35
@jaipsah It looks like you had some connection problem from your side. So I'm closing this now as we have nothing to do with it. Feel free to ask questions like this to our [Slack channel](https://polymer.slack.com/messages/C6ULJ2F7S).

**Closed by web-padawan** 2018-01-15 08:35 UTC
