### ISSUE TITLE
deselected function returning empty array

### ISSUE THREAD

**Issue by musti2** [vaadin/vaadin-grid#274] opened 2015-11-26 00:14 UTC
Hi Team,

I'm trying to toggle inspect if a row has been selected or deselected, however, the function grid.selection.deselected() is always returning an empty Array..

grid.addEventListener('selected-items-changed', function() {
   $log.info(grid.selection.selected()); // returns items that have been selected
   $log.info(grid.selection.deselected(); // always returns empty array
});

**Comment by jounik** [comment] 2015-11-26 11:19
Hi, and thanks for reporting. This is actually a duplicate of #248, so you can track the progress there.

**Closed by jounik** 2015-11-26 11:19 UTC

**Comment by musti2** [comment] 2015-11-27 01:25
Ah awesome. Thank you! Nice job on the grid too!
