### ISSUE TITLE
height-by-rows doesn't work inside a vertical layout

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-grid#1503] opened 2018-11-22 08:17 UTC
A grid with `heightByRows` enabled behaves unexpectedly if placed inside a `<vaadin-vertical-layout>` with a defined height.

```
<vaadin-vertical-layout style="height: 500px">
  <div>
    <vaadin-button raised id="add-btn">Add Item</vaadin-button>
    <vaadin-button raised id="remove-btn">Remove Item</vaadin-button>
  </div>
  <vaadin-grid aria-label="Dynamic Data Example" height-by-rows>
    <vaadin-grid-column path="name.first" header="First name"></vaadin-grid-column>
    <vaadin-grid-column path="name.last" header="Last name"></vaadin-grid-column>
    <vaadin-grid-column path="email"></vaadin-grid-column>
  </vaadin-grid>
</vaadin-vertical-layout>
```

Setting `flex-basis: auto` for the host with `heightByRows` enabled seems to resolve the issue.

**Comment by limonte** [comment] 2018-11-22 08:32
Duplicate of https://github.com/vaadin/vaadin-grid/issues/1415

**Closed by limonte** 2018-11-22 08:32 UTC
Labels: issue-backlog

**Comment by limonte** [comment] 2018-11-23 11:21
> Setting flex-basis: auto for the host with heightByRows enabled seems to resolve the issue.

Nope, setting `flex-grow: 0` would help.
