### ISSUE TITLE
empty cell values cause grid lines to offset down a few pixels.

### ISSUE THREAD

**Issue by jclx** [vaadin/vaadin-grid#146] opened 2015-09-09 20:35 UTC
Empty cell values cause grid lines to offset down a few pixels.
The span element in the td is <span></span> causes grid line to be offset below grid line for cells with values.

**Comment by jounik** [comment] 2015-09-10 10:34
Can you add a test case? And in which browser are you seeing this? I couldn’t reproduce it by modifying the DOM using the browser inspector.

**Comment by jclx** [comment] 2015-09-10 14:19
It looks like our css conflicts with grid settings. We had tbody,th,tr,td defined with vertical-align: baseline; which caused the issue. Looks like th,tr,td inherit and tbody is set to middle unless it is already set, which causes the problem. So I am not sure if this is an issue or not. Close if not.

This example shows no line for empty values:
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<link rel="import" href="../../../bower_components/vaadin-components/vaadin-grid/vaadin-grid.html">
	<style>
		tbody,th,td,tr {
			vertical-align: baseline;
		}
	</style>
</head>
<body>
<vaadin-grid>
	<table>
		<colgroup>
			<col header-text="Name">
			<col header-text="Value">
			<col header-text="Value2">
			<col header-text="Progress">
		</colgroup>
		<tbody>
		<tr>
			<td>Project A</td>
			<td>10000</td>
			<td></td>
			<td>0.8</td>
		</tr>
		<tr>
			<td>Project B</td>
			<td></td>
			<td>10000</td>
			<td>0.8</td>
		</tr>
		</tbody>
	</table>
</vaadin-grid>
</body>
</html>

**Comment by jounik** [comment] 2015-09-10 14:29
Alright, now I see it.

The problem is that those styles are not prevented from leaking into any web components. The way it is handled in Polymer, is that you should define you document level styles using the `<style is="custom-style">` tag, which will in effect do the style scoping for you. Polymer will rewrite those selectors for you on the fly, and they will look something like this:

```css
:not(.style-scope) tbody,
:not(.style-scope) th,
:not(.style-scope) td,
:not(.style-scope) tr {
  vertical-align: baseline;
}
```

I’m a little unsure if we should introduce a more specific override for e.g. vertical-align in the vaadin-grid styles. But that would avoid this issue at least, if you are not able to scope the styles yourself.

**Comment by jclx** [comment] 2015-09-10 18:30
The vertical-align is coming from a standard reset.css from internet which is a standard to reset all browsers to a common starting point. Like: http://html5doctor.com/html-5-reset-stylesheet/

**Comment by jounik** [comment] 2015-09-10 18:39
I was already expecting that, unfortunately.

A workaround that you can use for now is to override the styles for vaadin-grid yourself, until we figure out if we can/want to circumvent these sort of issues somehow (I didn’t test this, but something along these lines):

```html
<style is="custom-style">
  vaadin-grid ::content th,
  vaadin-grid ::content td {
    vertical-align: top;
  }
</style>
```

**Comment by jouni** [comment] 2017-03-23 08:52
Wontfix. The upcoming 2.0 does not suffer from the same problem, and native shadow being more broadly available also protects against these sort of style leaks.

**Closed by jouni** 2017-03-23 08:52 UTC
