### ISSUE TITLE
Custom tool tip for vaadin-grid hides behind the grid cell.

### ISSUE THREAD

**Issue by shanushka** [vaadin/vaadin-grid#1702] opened 2020-03-12 04:19 UTC
### Description

If a custom tooltip is used for a particular column in vaadin-grid then the tooltip hides behind the vaadin-grid. For resolving the problem, I had kept the custom tooltip outside of the vaadin grid and used mouse-leave and mouse-enter events to show the tooltip. But, due to race condition even when the mouse leaves the particular column the tooltip appears.

**Comment by web-padawan** [comment] 2020-03-27 18:47
Closing as duplicate of #842, please follow the discussion and explanations there.

In particular, the workaround idea suggested by https://github.com/vaadin/vaadin-grid/issues/842#issuecomment-291066913 is still valid.

**Closed by web-padawan** 2020-03-27 18:47 UTC
