### ISSUE TITLE
Row height is not updated when content changes

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#680] opened 2017-01-31 11:49 UTC
See how the row lines disappear when the column template changes from plain text to text inputs. The heights are corrected once you scroll back and forth:
![kapture 2017-01-31 at 13 43 41](https://cloud.githubusercontent.com/assets/66382/22463651/62c6c562-e7bb-11e6-8524-b067e11f486e.gif)

The same thing happens if you resize a column which has content that wraps to new lines:
![kapture 2017-01-31 at 13 49 20](https://cloud.githubusercontent.com/assets/66382/22463763/1b509946-e7bc-11e6-91e8-8a4a5acce11a.gif)

**Comment by jay8t6** [comment] 2017-10-18 21:54
+1

**Comment by tomivirkki** [comment] 2017-10-19 07:49
If the content changes dynamically you can invoke `grid.notifyResize()` to ask grid to recalculate its metrics (we really should add a demo for this).

In case of column resize this is called internally so the case of the second recording is no longer reproducible.

**Comment by tomivirkki** [comment] 2018-05-15 12:25
Closing as a duplicate of https://github.com/vaadin/vaadin-grid/issues/1060

**Closed by tomivirkki** 2018-05-15 12:25 UTC
