### ISSUE TITLE
zero height Component

### ISSUE THREAD

**Issue by zalevan** [vaadin/vaadin-grid#1557] opened 2019-02-07 12:20 UTC
I use two view with grids. I have boolean value and use ComponentRenderer<CheckBox, ...> for it column. 
When i first open grid all is ok. I see checkbox. Then i switch to another view and back. I see zero height for ComponentRenderer element and check box not visible.

**Comment by web-padawan** [comment] 2019-05-28 13:56
Closing as duplicate of https://github.com/vaadin/vaadin-grid-flow/issues/557 which is fixed by https://github.com/vaadin/flow/pull/5223

**Closed by web-padawan** 2019-05-28 13:56 UTC
