### ISSUE TITLE
Setting text-align: center on a parent element of the grid causes the column headers to shift to the right

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/vaadin-grid#943] opened 2017-08-09 11:09 UTC
When you add a `vaadin-grid` to a parent element which contains the `text-align: center` CSS rule, the headers of the grid are shifted to the right, making it look broken. Also a horizontal scrollbar is created due to the columns shift.

For example:
```
<div style="text-align: center">
    <vaadin-grid> ... </vaadin-grid>
</div>
```

A working example can be found here: https://jsbin.com/sipijelupe/edit?html,output

What I expect when the `text-align: center` is cascaded to the grid is that the text in the column headers become centralized inside the cell, without shifting the entire header row.

**Comment by web-padawan** [comment] 2017-08-09 12:34
Seems that adding explicit `left: 0` for [vaadin-grid-table-header](https://github.com/vaadin/vaadin-grid/blob/master/vaadin-grid-table-scroll-behavior.html#L31) and [vaadin-grid-table-footer](https://github.com/vaadin/vaadin-grid/blob/master/vaadin-grid-table-scroll-behavior.html#L37) fixes the issue, although it does not change the fact that you should for explicitly set `text-align` for cells due to [this row](https://github.com/vaadin/vaadin-grid/blob/master/vaadin-grid-table.html#L224).

**Comment by samiheikki** [comment] 2018-09-09 10:52
Issue is not reproducible with v5.2.0-alpha1.
Demo to verify fix: https://plnkr.co/edit/tkYhshy2UZqBHDefpfRN?p=preview
I'm closing the issue.

**Closed by samiheikki** 2018-09-09 10:52 UTC
Labels: issue-backlog
