### ISSUE TITLE
Sidebar button to show/hide columns is resized

### ISSUE THREAD

**Issue by nocquidant** [vaadin/vaadin-grid#334] opened 2016-03-22 10:52 UTC
I try to use vaadin-grid with www.getmdl.io and the window to show/hide columns is resized when items are unchecked. Thus, i cannot checked them any more.

See https://codepen.io/andiqo/pen/BKWgWa

Any help appreciated.
Thanks
--nick

**Comment by jounik** [comment] 2016-03-22 11:30
Thanks for the report. This issue is caused by #197, using the class `.hidden` in the dropdown for the hidden column items, and MDL having `display: none !important;` for that class name.

Closing this one as duplicate. You can subscribe to #197 to get updates when we fix this.

As a workaround, add the following to your CSS:

```css
.vaadin-grid-sidebar .hidden {
  display: block !important;
}
```

**Closed by jounik** 2016-03-22 11:30 UTC

**Comment by nocquidant** [comment] 2016-03-22 12:20
Many thanks for the quick answer.
--nick
